import { DriverReadiness, ReadinessQuestionDef } from "../types";
import { 
  Map, BedDouble, Pill, Coffee, ClipboardCheck, Smartphone, Timer, Navigation, LifeBuoy, CloudSunRain, LogOut, SteeringIcon
} from './icons';
import {
  VehicleBodyIcon, PlateIcon, WheelIcon, TyrePressureIcon, SpareTyreIcon, LeakIcon, LampIcon, SignalIcon, MirrorIcon, WiperIcon, BatteryIcon, FluidsIcon, FuelIcon, HornIcon, BrakesIcon, ACIcon, IVMSIcon, SeatBeltIcon, FireExtIcon, FirstAidIcon, EmergencyToolsIcon, CommToolsIcon, LuggageIcon, DocumentsIcon, BatteryCharging, Zap, PlugZap
} from './icons';

export const INITIAL_READINESS: DriverReadiness = {
  declaration: false,
  finalConfirmation: false,
  answers: {},
  status: 'pending'
};

export const READINESS_QUESTIONS: ReadinessQuestionDef[] = [
  { id: 'q_rested', key: 'q_rested', critical: true, icon: BedDouble },
  { id: 'q_no_meds', key: 'q_no_meds', critical: true, icon: Pill },
  { id: 'q_break_plan', key: 'q_break_plan', critical: true, icon: Coffee },
  { id: 'q_vehicle_suitable', key: 'q_vehicle_suitable', critical: true, icon: ClipboardCheck },
  { id: 'q_emergency_kit', key: 'q_emergency_kit', critical: true, icon: Smartphone },
  { id: 'q_max_hours', key: 'q_max_hours', critical: true, icon: Timer },
  { id: 'q_gps_stop', key: 'q_gps_stop', critical: true, icon: Navigation },
  { id: 'q_emergency_proc', key: 'q_emergency_proc', critical: true, icon: LifeBuoy },
  { id: 'q_bad_weather', key: 'q_bad_weather', critical: true, icon: CloudSunRain },
];

export const TBT_TOPICS = [
  { id: 'tbt_driver_behaviour', titleKey: 'tbt_driver_behaviour_title', introKey: 'tbt_driver_behaviour_intro', pointsKey: 'tbt_driver_behaviour_points' },
  { id: 'tbt_driver_fitness', titleKey: 'tbt_driver_fitness_title', introKey: 'tbt_driver_fitness_intro', pointsKey: 'tbt_driver_fitness_points' },
  { id: 'tbt_vehicle_readiness', titleKey: 'tbt_vehicle_readiness_title', introKey: 'tbt_vehicle_readiness_intro', pointsKey: 'tbt_vehicle_readiness_points' },
  { id: 'tbt_journey_management', titleKey: 'tbt_journey_management_title', introKey: 'tbt_journey_management_intro', pointsKey: 'tbt_journey_management_points' },
  { id: 'tbt_road_weather', titleKey: 'tbt_road_weather_title', introKey: 'tbt_road_weather_intro', pointsKey: 'tbt_road_weather_points' },
];

export const GENERIC_CHECKLIST = [
  { id: 1, key: 'body_damage', icon: VehicleBodyIcon },
  { id: 2, key: 'plates', icon: PlateIcon },
  { id: 3, key: 'tyres', icon: WheelIcon },
  { id: 4, key: 'tyre_pressure', icon: TyrePressureIcon },
  { id: 5, key: 'spare_tire', icon: SpareTyreIcon },
  { id: 6, key: 'fluid_leaks', icon: LeakIcon },
  { id: 7, key: 'lights', icon: LampIcon },
  { id: 8, key: 'indicators', icon: SignalIcon },
  { id: 9, key: 'mirrors', icon: MirrorIcon },
  { id: 10, key: 'wipers', icon: WiperIcon },
  { id: 11, key: 'battery', icon: BatteryIcon },
  { id: 12, key: 'fluid_levels', icon: FluidsIcon },
  { id: 13, key: 'fuel', icon: FuelIcon },
  { id: 14, key: 'horn', icon: HornIcon },
  { id: 15, key: 'brakes', icon: BrakesIcon },
  { id: 16, key: 'ac', icon: ACIcon },
  { id: 17, key: 'monitoring_system', icon: IVMSIcon },
  { id: 18, key: 'seat_belts', icon: SeatBeltIcon },
  { id: 19, key: 'fire_ext', icon: FireExtIcon },
  { id: 20, key: 'safety_kit', icon: FirstAidIcon },
  { id: 21, key: 'tools', icon: EmergencyToolsIcon },
  { id: 22, key: 'comm_tools', icon: CommToolsIcon },
  { id: 23, key: 'load_securing', icon: LuggageIcon },
  { id: 24, key: 'vehicle_docs', icon: DocumentsIcon },
];

export const ELECTRIC_CHECKLIST = [
  { id: 1, key: 'body_damage', icon: VehicleBodyIcon },
  { id: 2, key: 'plates', icon: PlateIcon },
  { id: 3, key: 'tyres', icon: WheelIcon },
  { id: 4, key: 'tyre_pressure', icon: TyrePressureIcon },
  { id: 5, key: 'spare_tire', icon: SpareTyreIcon },
  { id: 6, key: 'fluid_leaks', icon: LeakIcon },
  { id: 7, key: 'lights', icon: LampIcon },
  { id: 8, key: 'indicators', icon: SignalIcon },
  { id: 9, key: 'mirrors', icon: MirrorIcon },
  { id: 10, key: 'wipers', icon: WiperIcon },
  { id: 11, key: 'battery', icon: BatteryIcon },
  { id: 12, key: 'ev_hv_battery', icon: BatteryCharging },
  { id: 13, key: 'ev_charge_level', icon: Zap },
  { id: 14, key: 'ev_charging_port', icon: PlugZap },
  { id: 15, key: 'horn', icon: HornIcon },
  { id: 16, key: 'brakes', icon: BrakesIcon },
  { id: 17, key: 'ac', icon: ACIcon },
  { id: 18, key: 'monitoring_system', icon: IVMSIcon },
  { id: 19, key: 'seat_belts', icon: SeatBeltIcon },
  { id: 20, key: 'fire_ext', icon: FireExtIcon },
  { id: 21, key: 'safety_kit', icon: FirstAidIcon },
  { id: 22, key: 'tools', icon: EmergencyToolsIcon },
  { id: 23, key: 'comm_tools', icon: CommToolsIcon },
  { id: 24, key: 'vehicle_docs', icon: DocumentsIcon },
];

export const HEAVY_BUS_CHECKLIST = [
  { id: 1, key: 'body_damage', icon: VehicleBodyIcon },
  { id: 2, key: 'tyres', icon: WheelIcon },
  { id: 3, key: 'tyre_pressure', icon: TyrePressureIcon },
  { id: 4, key: 'fluid_leaks', icon: LeakIcon },
  { id: 5, key: 'lights', icon: LampIcon },
  { id: 6, key: 'indicators', icon: SignalIcon },
  { id: 7, key: 'mirrors', icon: MirrorIcon },
  { id: 8, key: 'wipers', icon: WiperIcon },
  { id: 9, key: 'battery', icon: BatteryIcon },
  { id: 10, key: 'fluid_levels', icon: FluidsIcon },
  { id: 11, key: 'fuel', icon: FuelIcon },
  { id: 12, key: 'warning_alarms', icon: HornIcon },
  { id: 13, key: 'brakes', icon: BrakesIcon },
  { id: 14, key: 'ac', icon: ACIcon },
  { id: 15, key: 'monitoring_system', icon: IVMSIcon },
  { id: 16, key: 'seat_belts', icon: SeatBeltIcon },
  { id: 17, key: 'fire_ext', icon: FireExtIcon },
  { id: 18, key: 'safety_kit', icon: FirstAidIcon },
  { id: 19, key: 'tools', icon: EmergencyToolsIcon },
  { id: 20, key: 'comm_tools', icon: CommToolsIcon },
  { id: 21, key: 'load_securing', icon: LuggageIcon },
  { id: 22, key: 'vehicle_docs', icon: DocumentsIcon },
  { id: 23, key: 'steering', icon: SteeringIcon },
  { id: 24, key: 'emergency_exits', icon: LogOut },
];

export const CHECKLIST_STATUS_LABELS: Record<string, { pass: { ar: string, en: string }, fail: { ar: string, en: string } }> = {
  battery: { pass: { ar: 'مشحونة', en: 'Charged' }, fail: { ar: 'ضعيفة', en: 'Weak' } },
  horn: { pass: { ar: 'يعمل', en: 'Working' }, fail: { ar: 'لا يعمل', en: 'Not Working' } },
  warning_alarms: { pass: { ar: 'تعمل', en: 'Working' }, fail: { ar: 'لا تعمل', en: 'Not Working' } },
  seat_belts: { pass: { ar: 'سليمة', en: 'Intact' }, fail: { ar: 'تالفة', en: 'Damaged' } },
  fuel: { pass: { ar: 'كافٍ', en: 'Sufficient' }, fail: { ar: 'منخفض', en: 'Low' } },
  wipers: { pass: { ar: 'سليمة', en: 'Intact' }, fail: { ar: 'تالفة', en: 'Damaged' } },
  lights: { pass: { ar: 'تعمل', en: 'Working' }, fail: { ar: 'لا تعمل', en: 'Not Working' } },
  indicators: { pass: { ar: 'تعمل', en: 'Working' }, fail: { ar: 'لا تعمل', en: 'Not Working' } },
  mirrors: { pass: { ar: 'سليمة', en: 'Intact' }, fail: { ar: 'متضررة', en: 'Damaged' } },
  brakes: { pass: { ar: 'سليمة', en: 'Intact' }, fail: { ar: 'ضعيفة', en: 'Weak' } },
  plates: { pass: { ar: 'واضحة', en: 'Clear' }, fail: { ar: 'غير واضحة', en: 'Unclear' } },
  body_damage: { pass: { ar: 'سليم', en: 'Intact' }, fail: { ar: 'ضرر', en: 'Damage' } },
  tyres: { pass: { ar: 'سليمة', en: 'Intact' }, fail: { ar: 'تالفة', en: 'Damaged' } },
  tyre_pressure: { pass: { ar: 'صحيح', en: 'Correct' }, fail: { ar: 'غير صحيح', en: 'Incorrect' } },
  fluid_leaks: { pass: { ar: 'لا توجد', en: 'No Leaks' }, fail: { ar: 'تسريب', en: 'Leaks' } },
  fluid_levels: { pass: { ar: 'مكتملة', en: 'Full' }, fail: { ar: 'ناقصة', en: 'Low' } },
  fire_ext: { pass: { ar: 'صالحة', en: 'Valid' }, fail: { ar: 'منتهية', en: 'Expired' } },
  safety_kit: { pass: { ar: 'مكتملة', en: 'Complete' }, fail: { ar: 'ناقصة', en: 'Incomplete' } },
  tools: { pass: { ar: 'مكتملة', en: 'Complete' }, fail: { ar: 'ناقصة', en: 'Incomplete' } },
  ac: { pass: { ar: 'بارد', en: 'Cool' }, fail: { ar: 'ضعيف', en: 'Weak' } },
  monitoring_system: { pass: { ar: 'يعمل', en: 'Working' }, fail: { ar: 'معطل', en: 'Faulty' } },
  vehicle_docs: { pass: { ar: 'صالحة', en: 'Valid' }, fail: { ar: 'منتهية', en: 'Expired' } },
  spare_tire: { pass: { ar: 'سليم', en: 'Intact' }, fail: { ar: 'تالف', en: 'Damaged' } },
  comm_tools: { pass: { ar: 'تعمل', en: 'Working' }, fail: { ar: 'لا تعمل', en: 'Not Working' } },
  load_securing: { pass: { ar: 'آمن', en: 'Secure' }, fail: { ar: 'غير امنه', en: 'Unsecured' } },
  steering: { pass: { ar: 'سليمة', en: 'Normal' }, fail: { ar: 'خلل', en: 'Faulty' } },
  emergency_exits: { pass: { ar: 'سليمة', en: 'Functional' }, fail: { ar: 'معطلة', en: 'Obstructed' } },
  doors_steps: { pass: { ar: 'سليمة', en: 'Safe' }, fail: { ar: 'تالفة', en: 'Unsafe' } },
  ev_hv_battery: { pass: { ar: 'سليمة', en: 'Normal' }, fail: { ar: 'خلل', en: 'Faulty' } },
  ev_charge_level: { pass: { ar: 'كافٍ', en: 'Sufficient' }, fail: { ar: 'منخفض', en: 'Low' } },
  ev_charging_port: { pass: { ar: 'سليم', en: 'Intact' }, fail: { ar: 'تالف', en: 'Damaged' } },
  toilet_condition: { pass: { ar: 'نظيفة', en: 'Clean' }, fail: { ar: 'غير نظيفة', en: 'Not Clean' } },
  drinking_water: { pass: { ar: 'متوفر', en: 'Available' }, fail: { ar: 'غير متوفر', en: 'Not Available' } },
  refrigerators: { pass: { ar: 'تعمل', en: 'Working' }, fail: { ar: 'معطلة', en: 'Faulty' } },
  tv_system: { pass: { ar: 'يعمل', en: 'Working' }, fail: { ar: 'معطل', en: 'Faulty' } },
  wifi_system: { pass: { ar: 'يعمل', en: 'Working' }, fail: { ar: 'معطل', en: 'Faulty' } },
  guardian_system: { pass: { ar: 'يعمل', en: 'Working' }, fail: { ar: 'معطل', en: 'Faulty' } },
  aed_device: { pass: { ar: 'صالح', en: 'Valid' }, fail: { ar: 'منتهي', en: 'Expired' } },
  safety_signage: { pass: { ar: 'واضحة', en: 'Clear' }, fail: { ar: 'مفقودة', en: 'Missing' } },
  tyres_condition: { pass: { ar: 'سليمة', en: 'Intact' }, fail: { ar: 'تالفة', en: 'Damaged' } },
  internal_mirrors: { pass: { ar: 'سليمة', en: 'Intact' }, fail: { ar: 'متضررة', en: 'Damaged' } },
  external_mirrors: { pass: { ar: 'سليمة', en: 'Intact' }, fail: { ar: 'متضررة', en: 'Damaged' } },
  brake_lights: { pass: { ar: 'تعمل', en: 'Working' }, fail: { ar: 'لا تعمل', en: 'Not Working' } },
  steering_fluid: { pass: { ar: 'كافٍ', en: 'Sufficient' }, fail: { ar: 'منخفض', en: 'Low' } },
};

export const CHECKLIST_TOOLTIPS: Record<string, { ar: string, en: string }> = {
  body_damage: { ar: 'فحص الهيكل الخارجي للمركبة للتأكد من خلوه من الصدمات أو أي أضرار قد تؤثر على السلامة', en: 'Inspect external body to ensure no dents or damage affecting safety' },
  plates: { ar: 'التحقق من وجود لوحات المركبة وتثبيتها بشكل صحيح ووضوح الأرقام وعدم وجود تلف', en: 'Verify presence and secure fixing of plates with clear numbers and no damage' },
  tyres: { ar: 'فحص حالة الإطارات للتأكد من عدم وجود تآكل مفرط أو تشققات أو انتفاخ', en: 'Check tyre condition for excessive wear, cracks, or bulging' },
  tyre_pressure: { ar: 'التأكد من أن ضغط الهواء في الإطارات ضمن الحدود الموصى بها', en: 'Ensure tyre pressure is within recommended limits' },
  spare_tire: { ar: 'التحقق من توفر الإطار الاحتياطي وسلامته وجاهزيته للاستخدام عند الطوارئ', en: 'Confirm spare tyre availability, integrity, and emergency readiness' },
  fluid_leaks: { ar: 'فحص أسفل المركبة للتأكد من عدم وجود أي تسريب للزيوت أو السوائل', en: 'Check under vehicle for any oil or fluid leaks' },
  lights: { ar: 'التأكد من عمل جميع المصابيح الأمامية والخلفية', en: 'Ensure all front and rear lights are functional' },
  indicators: { ar: 'فحص إشارات الانعطاف وأضواء التحذير والتأكد من عملها بوضوح', en: 'Check turn signals and hazard lights for clarity and function' },
  mirrors: { ar: 'التحقق من سلامة ونظافة الزجاج الامامي والمرايا وإمكانية ضبطها لتوفير رؤية واضحة', en: 'Verify safety and cleanliness of windshield and mirrors with clear visibility' },
  wipers: { ar: 'فحص عمل مساحات الزجاج وسلامة الشفرات وتوفر ماء المساحات', en: 'Inspect wiper operation, blade integrity, and fluid availability' },
  battery: { ar: 'التحقق من ثبات البطارية وسلامة الأقطاب وعدم وجود تآكل أو ضعف في التشغيل', en: 'Check battery stability, terminal safety, and no corrosion or weak start' },
  fluid_levels: { ar: 'فحص مستويات السوائل الأساسية مثل زيت المحرك وسائل التبريد وزيت الفرامل', en: 'Check essential fluid levels like engine oil, coolant, and brake fluid' },
  fuel: { ar: 'التأكد من توفر كمية وقود كافية لإتمام الرحلة المخطط لها', en: 'Ensure sufficient fuel to complete the planned journey' },
  horn: { ar: 'التحقق من عمل البوق وصوت التنبيه بوضوح', en: 'Verify horn operation and clear alert sound' },
  brakes: { ar: 'التأكد من كفاءة عمل الفرامل وعدم وجود ضعف أو أصوات غير طبيعية', en: 'Ensure brake efficiency and no weakness or abnormal sounds' },
  ac: { ar: 'فحص نظام التكييف للتأكد من كفاءته وقدرته على التبريد', en: 'Inspect AC system for efficiency and cooling capacity' },
  monitoring_system: { ar: 'التأكد من توفر نظام المراقبة والتتبع والكاميرات', en: 'Ensure the monitoring and tracking system and cameras are present' },
  seat_belts: { ar: 'فحص سلامة المقاعد وأحزمة الأمان والتأكد من ثباتها وآلية القفل', en: 'Inspect seat and belt safety, stability, and locking mechanism' },
  fire_ext: { ar: 'التحقق من توفر طفاية الحريق وصلاحيتها وسهولة الوصول إليها', en: 'Verify fire extinguisher availability, validity, and accessibility' },
  safety_kit: { ar: 'التأكد من صلاحية حقيبة الإسعافات الأولية واكتمال محتوياتها الأساسية', en: 'Verify first aid kit validity and completion of basic contents' },
  tools: { ar: 'التحقق من توفر أدوات الطوارئ مثل مثلث التحذير والرافعة ومفتاح العجلات', en: 'Verify emergency tools like warning triangle, jack, and wheel wrench' },
  comm_tools: { ar: 'التأكد من جاهزية وسائل الاتصال مثل الهاتف أو أجهزة الاتصال', en: 'Ensure communication tools like phone or radio are ready' },
  load_securing: { ar: 'التحقق من تثبيت الحمولة أو الأمتعة بإحكام لمنع تحركها أثناء القيادة', en: 'Verify cargo or luggage is securely fastened to prevent movement' },
  vehicle_docs: { ar: 'التأكد من توفر وثائق المركبة الرسمية وسريانها', en: 'Ensure official vehicle documents are available and valid' },
  doors_steps: { ar: 'سلامة الأبواب ودرج الصعود', en: 'Safe doors and boarding steps' },
  emergency_exits: { ar: 'فحص مخارج الطوارئ وسهولة فتحها', en: 'Check functional emergency exits' },
  steering: { ar: 'فحص سلاسة حركة عجلة القيادة', en: 'Check smooth steering wheel' },
  warning_alarms: { ar: 'تحقق من عمل تنبيه الرجوع للخلف', en: 'Check reverse alarm operation' },
};

export const AMBULANCE_TOOLTIPS: Record<string, { ar: string, en: string }> = { ...CHECKLIST_TOOLTIPS };

export const HEAVY_BUS_TOOLTIPS: Record<string, { ar: string, en: string }> = {
  body_damage: { ar: 'فحص الهيكل الخارجي للمركبة للتأكد من خلوه من الصدمات أو أي أضرار قد تؤثر على السلامة', en: 'Inspect external body to ensure no dents or damage affecting safety' },
  tyres: { ar: 'فحص حالة الإطارات للتأكد من عدم وجود تآكل مفرط أو تشققات أو انتفاخ', en: 'Check tyre condition for excessive wear, cracks, or bulging' },
  tyre_pressure: { ar: 'التأكد من أن ضغط الهواء في الإطارات ضمن الحدود الموصى بها', en: 'Ensure tyre pressure is within recommended limits' },
  fluid_leaks: { ar: 'فحص أسفل المركبة للتأكد من عدم وجود أي تسريب للزيوت أو السوائل', en: 'Check under vehicle for any oil or fluid leaks' },
  lights: { ar: 'التأكد من عمل جميع المصابيح الأمامية والخلفية', en: 'Ensure all front and rear lights are functional' },
  indicators: { ar: 'فحص إشارات الانعطاف وأضواء التحذير والتأكد من عملها بوضوح', en: 'Check turn signals and hazard lights for clarity and function' },
  mirrors: { ar: 'التحقق من سلامة ونظافة الزجاج الامامي والمرايا وإمكانية ضبطها لتوفير رؤية واضحة', en: 'Verify safety and cleanliness of windshield and mirrors with clear visibility' },
  wipers: { ar: 'فحص عمل مساحات الزجاج وسلامة الشفرات وتوفر ماء المساحات', en: 'Inspect wiper operation, blade integrity, and fluid availability' },
  battery: { ar: 'التحقق من ثبات البطارية وسلامة الأقطاب وعدم وجود تآكل أو ضعف في التشغيل', en: 'Check battery stability, terminal safety, and no corrosion or weak start' },
  fluid_levels: { ar: 'فحص مستويات السوائل الأساسية مثل زيت المحرك، سائل التبريد، وزيت الفرامل', en: 'Check essential fluid levels like engine oil, coolant, and brake fluid' },
  fuel: { ar: 'التأكد من توفر كمية وقود كافية لإتمام الرحلة المخطط لها', en: 'Ensure sufficient fuel to complete the planned journey' },
  warning_alarms: { ar: 'التحقق من عمل البوق وتنبيه الرجوع إلى الخلف', en: 'Verify horn and reverse alarm operation' },
  brakes: { ar: 'التأكد من كفاءة عمل الفرامل وعدم وجود ضعف أو أصوات غير طبيعية', en: 'Ensure brake efficiency and no weakness or abnormal sounds' },
  ac: { ar: 'فحص نظام التكييف للتأكد من كفاءته وقدرته على التبريد', en: 'Inspect AC system for efficiency and cooling capacity' },
  monitoring_system: { ar: 'التحقق من جاهزية نظام المراقبة والتتبع والكاميرات وعمله بشكل سليم', en: 'Verify monitoring, tracking, and camera readiness and function' },
  seat_belts: { ar: 'فحص سلامة المقاعد وأحزمة الأمان والتأكد من ثباتها وآلية القفل', en: 'Inspect seat and belt safety, stability, and locking mechanism' },
  fire_ext: { ar: 'التحقق من توفر طفاية الحريق وصلاحيتها وسهولة الوصول إليها', en: 'Verify fire extinguisher availability, validity, and accessibility' },
  safety_kit: { ar: 'التحقق من صلاحية الإسعافات الأولية واكتمال معداتها وتوفر جهاز AED', en: 'Verify first aid validity, complete equipment, and AED presence' },
  tools: { ar: 'التحقق من توفر أدوات الطوارئ مثل مثلث التحذير، المياه الاحتياطية، السترات العاكسة، والإضاءة الاحتياطية', en: 'Verify emergency tools like warning triangle, spare water, and vests' },
  comm_tools: { ar: 'التأكد من جاهزية وسائل الاتصال مثل الهاتف أو أجهزة الاتصال اللاسلكي', en: 'Ensure communication tools like phone or radio are ready' },
  load_securing: { ar: 'التحقق من تثبيت الحمولة أو الأمتعة بإحكام لمنع تحركها أثناء القيادة', en: 'Verify cargo or luggage is securely fastened to prevent movement' },
  vehicle_docs: { ar: 'التأكد من توفر وثائق المركبة الرسمية وسريانها', en: 'Ensure official vehicle documents are available and valid' },
  steering: { ar: 'التحقق من سلاسة حركة المقود وعدم وجود اهتزازات أو أصوات غير طبيعية', en: 'Check steering smoothness and no vibrations or abnormal sounds' },
  emergency_exits: { ar: 'فحص مخارج الطوارئ للتأكد من سلامتها وسهولة فتحها وعدم وجود عوائق', en: 'Inspect emergency exits for safety, ease of opening, and no obstructions' },
};

export const ELECTRIC_TOOLTIPS: Record<string, { ar: string, en: string }> = {
  ...CHECKLIST_TOOLTIPS,
  battery: { ar: 'فحص البطارية المساعدة (12V) والتأكد من سلامة الأقطاب وعدم وجود تآكل أو ضعف في التشغيل', en: 'Check 12V auxiliary battery stability, terminal safety, and no corrosion or weak start' },
  fluid_leaks: { ar: 'فحص أسفل المركبة للتأكد من عدم وجود تسريب لسائل تبريد البطارية أو سائل الفرامل', en: 'Check under vehicle for battery coolant or brake fluid leaks' },
  ev_hv_battery: { ar: 'فحص بطارية الجهد العالي (HV) للتأكد من سلامة التوصيلات وعدم وجود تسريب أو تلف في العازل', en: 'Inspect HV battery for safe connections, no leaks, and intact insulation' },
  ev_charge_level: { ar: 'التأكد من أن مستوى الشحن (SOC%) كافٍ لإتمام الرحلة المخطط لها', en: 'Verify battery charge level (SOC%) is sufficient to complete the planned journey' },
  ev_charging_port: { ar: 'فحص منفذ الشحن والكابل للتأكد من سلامتهما وعدم وجود تلف أو تآكل', en: 'Check charging port and cable for integrity, no damage or corrosion' },
};
