import { DriverReadiness, ReadinessQuestionDef } from "../types";
import { 
  Map, BedDouble, Pill, Coffee, ClipboardCheck, Smartphone, Timer, Navigation, LifeBuoy, CloudSunRain, LogOut, SteeringIcon
} from './icons';
import {
  VehicleBodyIcon, PlateIcon, WheelIcon, TyrePressureIcon, SpareTyreIcon, LeakIcon, LampIcon, SignalIcon, MirrorIcon, WiperIcon, BatteryIcon, FluidsIcon, FuelIcon, HornIcon, BrakesIcon, ACIcon, IVMSIcon, SeatBeltIcon, FireExtIcon, FirstAidIcon, EmergencyToolsIcon, CommToolsIcon, LuggageIcon, DocumentsIcon, BatteryCharging, Zap, PlugZap,
  EVTireRepairIcon, EVChargingCableIcon
} from './icons';

export const INITIAL_READINESS: DriverReadiness = {
  declaration: false,
  finalConfirmation: false,
  answers: {},
  status: 'pending'
};

export const READINESS_QUESTIONS: ReadinessQuestionDef[] = [
  { id: 'q_rested', key: 'q_rested', critical: true, icon: BedDouble },
  { id: 'q_no_meds', key: 'q_no_meds', critical: true, icon: Pill },
  { id: 'q_break_plan', key: 'q_break_plan', critical: true, icon: Coffee },
  { id: 'q_vehicle_suitable', key: 'q_vehicle_suitable', critical: true, icon: ClipboardCheck },
  { id: 'q_emergency_kit', key: 'q_emergency_kit', critical: true, icon: Smartphone },
  { id: 'q_max_hours', key: 'q_max_hours', critical: true, icon: Timer },
  { id: 'q_gps_stop', key: 'q_gps_stop', critical: true, icon: Navigation },
  { id: 'q_emergency_proc', key: 'q_emergency_proc', critical: true, icon: LifeBuoy },
  { id: 'q_bad_weather', key: 'q_bad_weather', critical: true, icon: CloudSunRain },
];

export const TBT_TOPICS = [
  { id: 'tbt_driver_behaviour', titleKey: 'tbt_driver_behaviour_title', introKey: 'tbt_driver_behaviour_intro', pointsKey: 'tbt_driver_behaviour_points' },
  { id: 'tbt_driver_fitness', titleKey: 'tbt_driver_fitness_title', introKey: 'tbt_driver_fitness_intro', pointsKey: 'tbt_driver_fitness_points' },
  { id: 'tbt_vehicle_readiness', titleKey: 'tbt_vehicle_readiness_title', introKey: 'tbt_vehicle_readiness_intro', pointsKey: 'tbt_vehicle_readiness_points' },
  { id: 'tbt_journey_management', titleKey: 'tbt_journey_management_title', introKey: 'tbt_journey_management_intro', pointsKey: 'tbt_journey_management_points' },
  { id: 'tbt_road_weather', titleKey: 'tbt_road_weather_title', introKey: 'tbt_road_weather_intro', pointsKey: 'tbt_road_weather_points' },
];

export const GENERIC_CHECKLIST = [
  { id: 1, key: 'body_damage', icon: VehicleBodyIcon },
  { id: 2, key: 'plates', icon: PlateIcon },
  { id: 3, key: 'tyres', icon: WheelIcon },
  { id: 4, key: 'tyre_pressure', icon: TyrePressureIcon },
  { id: 5, key: 'spare_tire', icon: SpareTyreIcon },
  { id: 6, key: 'fluid_leaks', icon: LeakIcon },
  { id: 7, key: 'lights', icon: LampIcon },
  { id: 8, key: 'indicators', icon: SignalIcon },
  { id: 9, key: 'mirrors', icon: MirrorIcon },
  { id: 10, key: 'wipers', icon: WiperIcon },
  { id: 11, key: 'battery', icon: BatteryIcon },
  { id: 12, key: 'fluid_levels', icon: FluidsIcon },
  { id: 13, key: 'fuel', icon: FuelIcon },
  { id: 14, key: 'horn', icon: HornIcon },
  { id: 15, key: 'brakes', icon: BrakesIcon },
  { id: 16, key: 'ac', icon: ACIcon },
  { id: 17, key: 'monitoring_system', icon: IVMSIcon },
  { id: 18, key: 'seat_belts', icon: SeatBeltIcon },
  { id: 19, key: 'fire_ext', icon: FireExtIcon },
  { id: 20, key: 'safety_kit', icon: FirstAidIcon },
  { id: 21, key: 'tools', icon: EmergencyToolsIcon },
  { id: 22, key: 'comm_tools', icon: CommToolsIcon },
  { id: 23, key: 'load_securing', icon: LuggageIcon },
  { id: 24, key: 'vehicle_docs', icon: DocumentsIcon },
];

export const ELECTRIC_CHECKLIST = [
  { id: 1, key: 'body_damage', icon: VehicleBodyIcon },
  { id: 2, key: 'ev_charge_level', icon: Zap },
  { id: 3, key: 'tyres', icon: WheelIcon },
  { id: 4, key: 'tyre_pressure', icon: TyrePressureIcon },
  { id: 5, key: 'tire_repair_kit', icon: EVTireRepairIcon },
  { id: 6, key: 'fluid_leaks', icon: LeakIcon },
  { id: 7, key: 'lights', icon: LampIcon },
  { id: 8, key: 'indicators', icon: SignalIcon },
  { id: 9, key: 'mirrors', icon: MirrorIcon },
  { id: 10, key: 'wipers', icon: WiperIcon },
  { id: 11, key: 'battery', icon: BatteryIcon },
  { id: 12, key: 'fluid_levels', icon: FluidsIcon },
  { id: 13, key: 'ev_hv_battery', icon: BatteryCharging },
  { id: 14, key: 'horn', icon: HornIcon },
  { id: 15, key: 'brakes', icon: BrakesIcon },
  { id: 16, key: 'ac', icon: ACIcon },
  { id: 17, key: 'monitoring_system', icon: IVMSIcon },
  { id: 18, key: 'seat_belts', icon: SeatBeltIcon },
  { id: 19, key: 'fire_ext', icon: FireExtIcon },
  { id: 20, key: 'safety_kit', icon: FirstAidIcon },
  { id: 21, key: 'tools', icon: EmergencyToolsIcon },
  { id: 22, key: 'charging_cable', icon: EVChargingCableIcon },
  { id: 23, key: 'luggage', icon: LuggageIcon },
  { id: 24, key: 'ev_charging_port', icon: PlugZap },
];

export const HEAVY_BUS_CHECKLIST = [
  { id: 1, key: 'body_damage', icon: VehicleBodyIcon },
  { id: 2, key: 'tyres', icon: WheelIcon },
  { id: 3, key: 'tyre_pressure', icon: TyrePressureIcon },
  { id: 4, key: 'fluid_leaks', icon: LeakIcon },
  { id: 5, key: 'lights', icon: LampIcon },
  { id: 6, key: 'indicators', icon: SignalIcon },
  { id: 7, key: 'mirrors', icon: MirrorIcon },
  { id: 8, key: 'wipers', icon: WiperIcon },
  { id: 9, key: 'battery', icon: BatteryIcon },
  { id: 10, key: 'fluid_levels', icon: FluidsIcon },
  { id: 11, key: 'fuel', icon: FuelIcon },
  { id: 12, key: 'warning_alarms', icon: HornIcon },
  { id: 13, key: 'brakes', icon: BrakesIcon },
  { id: 14, key: 'ac', icon: ACIcon },
  { id: 15, key: 'monitoring_system', icon: IVMSIcon },
  { id: 16, key: 'seat_belts', icon: SeatBeltIcon },
  { id: 17, key: 'fire_ext', icon: FireExtIcon },
  { id: 18, key: 'safety_kit', icon: FirstAidIcon },
  { id: 19, key: 'tools', icon: EmergencyToolsIcon },
  { id: 20, key: 'comm_tools', icon: CommToolsIcon },
  { id: 21, key: 'load_securing', icon: LuggageIcon },
  { id: 22, key: 'vehicle_docs', icon: DocumentsIcon },
  { id: 23, key: 'steering', icon: SteeringIcon },
  { id: 24, key: 'emergency_exits', icon: LogOut },
];

export const CHECKLIST_STATUS_LABELS: Record<string, { pass: { ar: string, en: string }, fail: { ar: string, en: string } }> = {
  battery: { pass: { ar: 'مشحونة', en: 'Charged' }, fail: { ar: 'ضعيفة', en: 'Weak' } },
  horn: { pass: { ar: 'يعمل', en: 'Working' }, fail: { ar: 'لا يعمل', en: 'Not Working' } },
  warning_alarms: { pass: { ar: 'تعمل', en: 'Working' }, fail: { ar: 'لا تعمل', en: 'Not Working' } },
  seat_belts: { pass: { ar: 'سليمة', en: 'Intact' }, fail: { ar: 'تالفة', en: 'Damaged' } },
  fuel: { pass: { ar: 'كافٍ', en: 'Sufficient' }, fail: { ar: 'منخفض', en: 'Low' } },
  wipers: { pass: { ar: 'سليمة', en: 'Intact' }, fail: { ar: 'تالفة', en: 'Damaged' } },
  lights: { pass: { ar: 'تعمل', en: 'Working' }, fail: { ar: 'لا تعمل', en: 'Not Working' } },
  indicators: { pass: { ar: 'تعمل', en: 'Working' }, fail: { ar: 'لا تعمل', en: 'Not Working' } },
  mirrors: { pass: { ar: 'سليمة', en: 'Intact' }, fail: { ar: 'متضررة', en: 'Damaged' } },
  brakes: { pass: { ar: 'سليمة', en: 'Intact' }, fail: { ar: 'ضعيفة', en: 'Weak' } },
  plates: { pass: { ar: 'واضحة', en: 'Clear' }, fail: { ar: 'غير واضحة', en: 'Unclear' } },
  body_damage: { pass: { ar: 'سليم', en: 'Intact' }, fail: { ar: 'ضرر', en: 'Damage' } },
  tyres: { pass: { ar: 'سليمة', en: 'Intact' }, fail: { ar: 'تالفة', en: 'Damaged' } },
  tyre_pressure: { pass: { ar: 'صحيح', en: 'Correct' }, fail: { ar: 'غير صحيح', en: 'Incorrect' } },
  fluid_leaks: { pass: { ar: 'لا توجد', en: 'No Leaks' }, fail: { ar: 'تسريب', en: 'Leaks' } },
  fluid_levels: { pass: { ar: 'مكتملة', en: 'Full' }, fail: { ar: 'ناقصة', en: 'Low' } },
  fire_ext: { pass: { ar: 'صالحة', en: 'Valid' }, fail: { ar: 'منتهية', en: 'Expired' } },
  fire_ext_2: { pass: { ar: 'صالحة', en: 'Valid' }, fail: { ar: 'منتهية', en: 'Expired' } },
  safety_kit: { pass: { ar: 'مكتملة', en: 'Complete' }, fail: { ar: 'ناقصة', en: 'Incomplete' } },
  tools: { pass: { ar: 'مكتملة', en: 'Complete' }, fail: { ar: 'ناقصة', en: 'Incomplete' } },
  ac: { pass: { ar: 'بارد', en: 'Cool' }, fail: { ar: 'ضعيف', en: 'Weak' } },
  monitoring_system: { pass: { ar: 'يعمل', en: 'Working' }, fail: { ar: 'معطل', en: 'Faulty' } },
  vehicle_docs: { pass: { ar: 'صالحة', en: 'Valid' }, fail: { ar: 'منتهية', en: 'Expired' } },
  spare_tire: { pass: { ar: 'سليم', en: 'Intact' }, fail: { ar: 'تالف', en: 'Damaged' } },
  comm_tools: { pass: { ar: 'تعمل', en: 'Working' }, fail: { ar: 'لا تعمل', en: 'Not Working' } },
  load_securing: { pass: { ar: 'آمن', en: 'Secure' }, fail: { ar: 'غير امنه', en: 'Unsecured' } },
  steering: { pass: { ar: 'سليمة', en: 'Normal' }, fail: { ar: 'خلل', en: 'Faulty' } },
  emergency_exits: { pass: { ar: 'سليمة', en: 'Functional' }, fail: { ar: 'معطلة', en: 'Obstructed' } },
  doors_steps: { pass: { ar: 'سليمة', en: 'Safe' }, fail: { ar: 'تالفة', en: 'Unsafe' } },
  ev_hv_battery: { pass: { ar: 'سليمة', en: 'Normal' }, fail: { ar: 'خلل', en: 'Faulty' } },
  ev_charge_level: { pass: { ar: 'كافٍ', en: 'Sufficient' }, fail: { ar: 'منخفض', en: 'Low' } },
  ev_charging_port: { pass: { ar: 'سليم', en: 'Intact' }, fail: { ar: 'تالف', en: 'Damaged' } },
  toilet_condition: { pass: { ar: 'نظيفة', en: 'Clean' }, fail: { ar: 'غير نظيفة', en: 'Not Clean' } },
  drinking_water: { pass: { ar: 'متوفر', en: 'Available' }, fail: { ar: 'غير متوفر', en: 'Not Available' } },
  refrigerators: { pass: { ar: 'تعمل', en: 'Working' }, fail: { ar: 'معطلة', en: 'Faulty' } },
  tv_system: { pass: { ar: 'يعمل', en: 'Working' }, fail: { ar: 'معطل', en: 'Faulty' } },
  wifi_system: { pass: { ar: 'يعمل', en: 'Working' }, fail: { ar: 'معطل', en: 'Faulty' } },
  guardian_system: { pass: { ar: 'يعمل', en: 'Working' }, fail: { ar: 'معطل', en: 'Faulty' } },
  aed_device: { pass: { ar: 'صالح', en: 'Valid' }, fail: { ar: 'منتهي', en: 'Expired' } },
  safety_signage: { pass: { ar: 'واضحة', en: 'Clear' }, fail: { ar: 'مفقودة', en: 'Missing' } },
  tyres_condition: { pass: { ar: 'سليمة', en: 'Intact' }, fail: { ar: 'تالفة', en: 'Damaged' } },
  internal_mirrors: { pass: { ar: 'سليمة', en: 'Intact' }, fail: { ar: 'متضررة', en: 'Damaged' } },
  external_mirrors: { pass: { ar: 'سليمة', en: 'Intact' }, fail: { ar: 'متضررة', en: 'Damaged' } },
  brake_lights: { pass: { ar: 'تعمل', en: 'Working' }, fail: { ar: 'لا تعمل', en: 'Not Working' } },
  steering_fluid: { pass: { ar: 'كافٍ', en: 'Sufficient' }, fail: { ar: 'منخفض', en: 'Low' } },
};

export const CHECKLIST_TOOLTIPS: Record<string, { ar: string, en: string }> = {
  body_damage: { ar: 'فحص الهيكل الخارجي للمركبة للتأكد من خلوه من الصدمات أو أي أضرار قد تؤثر على السلامة', en: 'Inspect external body to ensure no dents or damage affecting safety' },
  plates: { ar: 'التحقق من وجود لوحات المركبة وتثبيتها بشكل صحيح ووضوح الأرقام وعدم وجود تلف', en: 'Verify presence and secure fixing of plates with clear numbers and no damage' },
  tyres: { ar: 'فحص حالة الإطارات للتأكد من عدم وجود تآكل مفرط أو تشققات أو انتفاخ', en: 'Check tyre condition for excessive wear, cracks, or bulging' },
  tyre_pressure: { ar: 'التأكد من أن ضغط الهواء في الإطارات ضمن الحدود الموصى بها', en: 'Ensure tyre pressure is within recommended limits' },
  spare_tire: { ar: 'التحقق من توفر الإطار الاحتياطي وسلامته وجاهزيته للاستخدام عند الطوارئ', en: 'Confirm spare tyre availability, integrity, and emergency readiness' },
  fluid_leaks: { ar: 'فحص أسفل المركبة للتأكد من عدم وجود أي تسريب للزيوت أو السوائل', en: 'Check under vehicle for any oil or fluid leaks' },
  lights: { ar: 'التأكد من عمل جميع المصابيح الأمامية والخلفية', en: 'Ensure all front and rear lights are functional' },
  indicators: { ar: 'فحص إشارات الانعطاف وأضواء التحذير والتأكد من عملها بوضوح', en: 'Check turn signals and hazard lights for clarity and function' },
  mirrors: { ar: 'التحقق من سلامة ونظافة الزجاج الامامي والمرايا وإمكانية ضبطها لتوفير رؤية واضحة', en: 'Verify safety and cleanliness of windshield and mirrors with clear visibility' },
  wipers: { ar: 'فحص عمل مساحات الزجاج وسلامة الشفرات وتوفر ماء المساحات', en: 'Inspect wiper operation, blade integrity, and fluid availability' },
  battery: { ar: 'التحقق من ثبات البطارية وسلامة الأقطاب وعدم وجود تآكل أو ضعف في التشغيل', en: 'Check battery stability, terminal safety, and no corrosion or weak start' },
  fluid_levels: { ar: 'فحص مستويات السوائل الأساسية مثل زيت المحرك وسائل التبريد وزيت الفرامل', en: 'Check essential fluid levels like engine oil, coolant, and brake fluid' },
  fuel: { ar: 'التأكد من توفر كمية وقود كافية لإتمام الرحلة المخطط لها', en: 'Ensure sufficient fuel to complete the planned journey' },
  horn: { ar: 'التحقق من عمل البوق وصوت التنبيه بوضوح', en: 'Verify horn operation and clear alert sound' },
  brakes: { ar: 'التأكد من كفاءة عمل الفرامل وعدم وجود ضعف أو أصوات غير طبيعية', en: 'Ensure brake efficiency and no weakness or abnormal sounds' },
  ac: { ar: 'فحص نظام التكييف للتأكد من كفاءته وقدرته على التبريد', en: 'Inspect AC system for efficiency and cooling capacity' },
  monitoring_system: { ar: 'التأكد من توفر نظام المراقبة والتتبع والكاميرات', en: 'Ensure the monitoring and tracking system and cameras are present' },
  seat_belts: { ar: 'فحص سلامة المقاعد وأحزمة الأمان والتأكد من ثباتها وآلية القفل', en: 'Inspect seat and belt safety, stability, and locking mechanism' },
  fire_ext: { ar: 'التحقق من توفر طفاية الحريق وصلاحيتها وسهولة الوصول إليها', en: 'Verify fire extinguisher availability, validity, and accessibility' },
  fire_ext_2: { ar: 'التحقق من توفر طفاية الحريق الإضافية وصلاحيتها وسهولة الوصول إليها', en: 'Verify additional fire extinguisher availability, validity, and accessibility' },
  safety_kit: { ar: 'التأكد من صلاحية حقيبة الإسعافات الأولية واكتمال محتوياتها الأساسية', en: 'Verify first aid kit validity and completion of basic contents' },
  tools: { ar: 'التحقق من توفر أدوات الطوارئ مثل مثلث التحذير والرافعة ومفتاح العجلات', en: 'Verify emergency tools like warning triangle, jack, and wheel wrench' },
  comm_tools: { ar: 'التأكد من جاهزية وسائل الاتصال مثل الهاتف أو أجهزة الاتصال', en: 'Ensure communication tools like phone or radio are ready' },
  load_securing: { ar: 'التحقق من تثبيت الحمولة أو الأمتعة بإحكام لمنع تحركها أثناء القيادة', en: 'Verify cargo or luggage is securely fastened to prevent movement' },
  vehicle_docs: { ar: 'التأكد من توفر وثائق المركبة الرسمية وسريانها', en: 'Ensure official vehicle documents are available and valid' },
  doors_steps: { ar: 'سلامة الأبواب ودرج الصعود', en: 'Safe doors and boarding steps' },
  emergency_exits: { ar: 'فحص مخارج الطوارئ وسهولة فتحها', en: 'Check functional emergency exits' },
  steering: { ar: 'فحص سلاسة حركة عجلة القيادة', en: 'Check smooth steering wheel' },
  warning_alarms: { ar: 'تحقق من عمل تنبيه الرجوع للخلف', en: 'Check reverse alarm operation' },
  windows: { ar: 'فحص النوافذ والزجاج للتأكد من سلامتها وعدم وجود شروخ تعيق الرؤية', en: 'Inspect windows and glass for safety and ensure no cracks obscure visibility' },
  tyres_condition: { ar: 'فحص حالة الإطارات للتأكد من عدم وجود تآكل مفرط أو تشققات أو انتفاخ', en: 'Check tyre condition for excessive wear, cracks, or bulging' },
  external_mirrors: { ar: 'فحص المرايا الجانبية والخارجية للتأكد من سلامتها ونظافتها لتوفير رؤية واضحة', en: 'Inspect side and external mirrors for safety and cleanliness to provide clear visibility' },
  bumpers: { ar: 'التحقق من تثبيت المصدات الأمامية والخلفية بإحكام وعدم وجود تلفيات', en: 'Verify front and rear bumpers are securely fastened and undamaged' },
  reflectors: { ar: 'التأكد من وجود وسلامة العواكس الجانبية والخلفية', en: 'Ensure presence and integrity of side and rear reflectors' },
  vehicle_markings: { ar: 'التحقق من وضوح وسريان ملصقات المركبة التعريفية (مثل ملصقات أوبال)', en: 'Verify clarity and validity of vehicle identification markings (e.g. OPAL stickers)' },
  headlights: { ar: 'التأكد من عمل المصابيح الأمامية بجميع درجاتها بوضوح', en: 'Ensure all levels of headlights are working clearly' },
  brake_lights: { ar: 'فحص مصابيح الفرامل والتأكد من إضاءتها عند الضغط على الدواسة', en: 'Inspect brake lights to ensure they illuminate when pedal is pressed' },
  reverse_lights: { ar: 'التأكد من عمل مصابيح الرجوع للخلف عند وضع ناقل الحركة في وضعية الرجوع', en: 'Ensure reverse lights work when gear is in reverse' },
  reverse_alarm: { ar: 'التحقق من عمل جرس أو تنبيه الرجوع للخلف بوضوح', en: 'Verify reverse alarm operates clearly' },
  loose_fittings: { ar: 'التأكد من عدم وجود أجزاء أو براغي مفككة في هيكل المركبة أو أجزائها الخارجية', en: 'Ensure there are no loose parts or screws on the vehicle body or external parts' },
  bonnet_security: { ar: 'التحقق من إحكام إغلاق وقفل غطاء المحرك وعدم وجود ارتخاء', en: 'Verify hood is securely closed and locked without looseness' },
  battery_condition: { ar: 'فحص البطارية والتأكد من سلامة الأقطاب وعدم وجود تآكل أو تسريب', en: 'Check battery, ensure terminal safety, and no corrosion or leakage' },
  engine_oil: { ar: 'التحقق من مستوى زيت المحرك وجودته لضمان عمل المحرك بكفاءة', en: 'Check engine oil level and quality to ensure efficient engine operation' },
  brake_fluid: { ar: 'التأكد من مستوى سائل الفرامل لضمان كفاءة التوقف', en: 'Ensure brake fluid level for efficient stopping' },
  steering_fluid: { ar: 'فحص مستوى سائل نظام التوجيه (الدركسون) لضمان سلاسة التوجيه', en: 'Inspect steering fluid level to ensure smooth steering' },
  coolant_level: { ar: 'التأكد من مستوى سائل التبريد لمنع ارتفاع درجة حرارة المحرك', en: 'Ensure coolant level to prevent engine overheating' },
  washer_fluid: { ar: 'التحقق من توفر سائل تنظيف الزجاج الأمامي', en: 'Verify availability of windshield washer fluid' },
  belts_condition: { ar: 'فحص سيور المحرك للتأكد من عدم وجود تشققات أو ارتخاء أو تلف', en: 'Inspect engine belts for cracks, looseness, or damage' },
  belts_bearings: { ar: 'فحص حالة السيور ورولمان البلي للتأكد من خلوها من التلف أو التآكل', en: 'Inspect condition of belts and bearings for damage or wear' },
  wiring_condition: { ar: 'التحقق من سلامة التمديدات الكهربائية والأسلاك وعدم وجود أسلاك مكشوفة', en: 'Verify safety of electrical wiring and ensure no exposed wires' },
  hoses_condition: { ar: 'فحص خراطيم السوائل والتأكد من مرونتها وعدم وجود تشققات أو تسريبات', en: 'Inspect fluid hoses for flexibility and ensure no cracks or leaks' },
  driver_seat: { ar: 'التحقق من سلامة مقعد السائق وإمكانية تعديله وحزام الأمان الخاص به', en: 'Verify driver seat safety, adjustability, and its seat belt' },
  passenger_seats: { ar: 'فحص مقاعد الركاب للتأكد من سلامتها وثباتها وعدم وجود تلفيات', en: 'Inspect passenger seats for safety, stability, and no damages' },
  passenger_seat_belts: { ar: 'التأكد من توفر وعمل أحزمة الأمان لجميع مقاعد الركاب وسهولة قفلها', en: 'Ensure availability and function of seat belts for all passenger seats' },
  internal_mirrors: { ar: 'فحص مرآة الرؤية الخلفية الداخلية للتأكد من سلامتها ونظافتها', en: 'Inspect internal rearview mirror for safety and cleanliness' },
  dashboard: { ar: 'التحقق من سلامة لوحة القيادة وعدم وجود أجزاء مفككة أو مكسورة', en: 'Verify dashboard safety and ensure no loose or broken parts' },
  warning_indicators: { ar: 'التأكد من عمل جميع لمبات التحذير في لوحة القيادة وعدم وجود أخطاء مسجلة', en: 'Ensure all dashboard warning lights function and no errors are logged' },
  gauges: { ar: 'فحص عمل جميع العدادات (السرعة، الحرارة، الوقود) وتسجيلها للقيم الصحيحة', en: 'Inspect operation of all gauges (speed, temp, fuel) for correct values' },
  interior_lights: { ar: 'التأكد من عمل الإضاءة الداخلية للمركبة ومقاعد الركاب بوضوح', en: 'Ensure vehicle interior and passenger seating lights work clearly' },
  window_operation: { ar: 'التحقق من سلاسة عمل آليات رفع وخفض النوافذ وعدم وجود عوائق', en: 'Verify smooth operation of window mechanisms without obstruction' },
  curtains: { ar: 'التأكد من نظافة وسلامة الستائر الداخلية وإمكانية فتحها وإغلاقها بسهولة', en: 'Ensure cleanliness and safety of interior curtains and easy operation' },
  hand_brake: { ar: 'فحص كفاءة فرامل اليد (التوقف) في تثبيت المركبة', en: 'Inspect hand brake efficiency in securing the vehicle' },
  gear_lever: { ar: 'التحقق من سلاسة حركة ناقل السرعة (الجير) وعدم وجود مقاومة غير طبيعية', en: 'Verify smooth gear lever movement and no abnormal resistance' },
  safety_equipment: { ar: 'التأكد من توفر جميع معدات السلامة العامة في المركبة', en: 'Ensure availability of all general safety equipment in the vehicle' },
  emergency_hammers: { ar: 'التحقق من وجود مطارق كسر الزجاج في أماكنها المخصصة لحالات الطوارئ', en: 'Verify presence of glass-breaking hammers in designated emergency spots' },
  guardian_system: { ar: 'التأكد من عمل نظام مراقبة إرهاق السائق (الجارديان) وعدم وجود أعطال', en: 'Ensure driver fatigue monitoring system (Guardian) works without faults' },
  safety_signage: { ar: 'التحقق من وجود لوحات وملصقات إرشادية واضحة للركاب داخل المركبة', en: 'Verify presence of clear instructional signs and stickers for passengers inside' },
  aed_device: { ar: 'التأكد من توفر جهاز مزيل الرجفان الآلي (AED) وصلاحية بطاريته', en: 'Ensure availability of Automated External Defibrillator (AED) and battery validity' },
  general_interior: { ar: 'التحقق من نظافة وسلامة المقصورة الداخلية وعدم وجود أي تلفيات', en: 'Verify cleanliness and safety of the general interior and no damages' },
  warning_triangle: { ar: 'التأكد من توفر مثلث التحذير العاكس وصلاحيته للاستخدام', en: 'Ensure availability and usability of reflective warning triangle' },
  suspension_system: { ar: 'فحص نظام التعليق والمساعدين للتأكد من عدم وجود تهريب زيوت أو تلف', en: 'Inspect suspension and shock absorbers for leaks or damage' },
  exhaust_system: { ar: 'التأكد من سلامة نظام العادم (الشكمان) وعدم وجود تسريب للغازات', en: 'Ensure exhaust system integrity and no gas leaks' },
  sun_visors: { ar: 'التحقق من سلامة وثبات عاكسات الشمس وإمكانية تعديلها بسهولة', en: 'Verify safety and stability of sun visors and ease of adjustment' },
  rear_camera: { ar: 'التحقق من عمل كاميرات أو حساسات الرجوع للخلف ونظافتها لتوفير رؤية واضحة', en: 'Verify operation and cleanliness of rear camera or sensors to provide clear visibility' },
  wifi_system: { ar: 'التأكد من عمل نظام الإنترنت اللاسلكي (Wi-Fi) داخل الحافلة وتوفره للركاب', en: 'Ensure the Wi-Fi system is operational and available to passengers' },
  tv_system: { ar: 'فحص شاشات العرض وأنظمة الترفيه (TV) والتأكد من عملها ووضوح الصورة والصوت', en: 'Inspect TV screens and entertainment systems for operation, clear picture, and sound' },
  refrigerators: { ar: 'التحقق من عمل الثلاجات الداخلية وقدرتها على التبريد ونظافتها', en: 'Verify operation, cooling capacity, and cleanliness of internal refrigerators' },
  drinking_water: { ar: 'التأكد من توفر مياه الشرب ونظافة المبردات وجاهزيتها لاستخدام الركاب', en: 'Ensure drinking water availability, cooler cleanliness, and readiness for passengers' },
  toilet_condition: { ar: 'فحص نظافة دورة المياه وعمل أنظمة التصريف وتوفر المياه والمستلزمات الصحية', en: 'Inspect toilet cleanliness, drainage systems operation, and availability of water and sanitary supplies' },
  heavy_electric_switches: { ar: 'التحقق من عمل جميع المفاتيح الكهربائية الخاصة بمقاعد الركاب والأنظمة المستقلة', en: 'Ensure all passenger seat electrical switches and independent systems work' },
  heavy_electronic_gear: { ar: 'فحص استجابة وعمل أزرار نقل الحركة الإلكترونية بسلاسة ودون أخطاء', en: 'Verify smooth response and operation of electronic gear buttons without errors' },
  cargo_bed: { ar: 'التحقق من حالة صندوق التحميل وعدم وجود أضرار أو صدأ قد يؤثر على سلامة نقل الحمولة', en: 'Check the condition of the cargo bed for any damage or rust that could affect cargo safety' },
  cargo_area: { ar: 'فحص منطقة المقاعد الخلفية ومساحة التخزين الإضافية للتأكد من نظافتها وسلامتها', en: 'Inspect the rear seating and extra storage area for cleanliness and integrity' },
  cargo_tie_downs: { ar: 'التأكد من توفر وسلامة خطافات وأربطة التثبيت لضمان استقرار الحمولة أثناء القيادة', en: 'Ensure the availability and safety of tie-down hooks and straps for cargo stability during driving' },
  tonneau_cover: { ar: 'فحص غطاء صندوق التحميل والتأكد من إحكام إغلاقه وسهولة فتحه وعدم وجود تلف', en: 'Inspect the tonneau cover to ensure secure closing, smooth opening, and no damage' },
  tow_hitch: { ar: 'التحقق من سلامة وثبات مقطورة السحب (الهوك) وتوصيلاتها الكهربائية إن وجدت', en: 'Verify the safety and stability of the tow hitch and its electrical connections if applicable' },
  tailgate: { ar: 'التأكد من سلامة الباب الخلفي وعمله بسلاسة وإمكانية قفله بإحكام', en: 'Ensure the tailgate is in good condition, operates smoothly, and locks securely' },
};

export const AMBULANCE_TOOLTIPS: Record<string, { ar: string, en: string }> = {
  ...CHECKLIST_TOOLTIPS,
  emergency_lights: { ar: 'التحقق من عمل أضواء الطوارئ العلوية (اللواح) بجميع وضعياتها بوضوح', en: 'Ensure emergency overhead lights operate clearly in all modes' },
  siren_system: { ar: 'فحص جهاز التنبيه الصوتي (السارينة) بجميع أصواته للتأكد من عمله بكفاءة', en: 'Inspect siren system and all tones to ensure efficient operation' },
  patient_lighting: { ar: 'التأكد من عمل جميع مصابيح إضاءة المقصورة بكفاءة لتوفير رؤية واضحة للطاقم الطبي', en: 'Ensure cabin lighting operates efficiently to provide clear visibility for medical staff' },
  guardian_system: { ar: 'التأكد من عمل نظام كاميرات التتبع وعدم وجود أعطال', en: 'Ensure tracking camera system works without faults' },
  hazard_lights: { ar: 'التحقق من عمل أنوار التحذير الرباعية بوضوح', en: 'Verify hazard lights operate clearly' },
};

export const HEAVY_BUS_TOOLTIPS: Record<string, { ar: string, en: string }> = {
  ...CHECKLIST_TOOLTIPS,
  body_damage: { ar: 'فحص الهيكل الخارجي للمركبة للتأكد من خلوه من الصدمات أو أي أضرار قد تؤثر على السلامة', en: 'Inspect external body to ensure no dents or damage affecting safety' },
  tyres: { ar: 'فحص حالة الإطارات للتأكد من عدم وجود تآكل مفرط أو تشققات أو انتفاخ', en: 'Check tyre condition for excessive wear, cracks, or bulging' },
  tyre_pressure: { ar: 'التأكد من أن ضغط الهواء في الإطارات ضمن الحدود الموصى بها', en: 'Ensure tyre pressure is within recommended limits' },
  fluid_leaks: { ar: 'فحص أسفل المركبة للتأكد من عدم وجود أي تسريب للزيوت أو السوائل', en: 'Check under vehicle for any oil or fluid leaks' },
  lights: { ar: 'التأكد من عمل جميع المصابيح الأمامية والخلفية', en: 'Ensure all front and rear lights are functional' },
  indicators: { ar: 'فحص إشارات الانعطاف وأضواء التحذير والتأكد من عملها بوضوح', en: 'Check turn signals and hazard lights for clarity and function' },
  mirrors: { ar: 'التحقق من سلامة ونظافة الزجاج الامامي والمرايا وإمكانية ضبطها لتوفير رؤية واضحة', en: 'Verify safety and cleanliness of windshield and mirrors with clear visibility' },
  wipers: { ar: 'فحص عمل مساحات الزجاج وسلامة الشفرات وتوفر ماء المساحات', en: 'Inspect wiper operation, blade integrity, and fluid availability' },
  battery: { ar: 'التحقق من ثبات البطارية وسلامة الأقطاب وعدم وجود تآكل أو ضعف في التشغيل', en: 'Check battery stability, terminal safety, and no corrosion or weak start' },
  fluid_levels: { ar: 'فحص مستويات السوائل الأساسية مثل زيت المحرك، سائل التبريد، وزيت الفرامل', en: 'Check essential fluid levels like engine oil, coolant, and brake fluid' },
  fuel: { ar: 'التأكد من توفر كمية وقود كافية لإتمام الرحلة المخطط لها', en: 'Ensure sufficient fuel to complete the planned journey' },
  warning_alarms: { ar: 'التحقق من عمل البوق وتنبيه الرجوع إلى الخلف', en: 'Verify horn and reverse alarm operation' },
  brakes: { ar: 'التأكد من كفاءة عمل الفرامل وعدم وجود ضعف أو أصوات غير طبيعية', en: 'Ensure brake efficiency and no weakness or abnormal sounds' },
  ac: { ar: 'فحص نظام التكييف للتأكد من كفاءته وقدرته على التبريد', en: 'Inspect AC system for efficiency and cooling capacity' },
  monitoring_system: { ar: 'التحقق من جاهزية نظام المراقبة والتتبع والكاميرات وعمله بشكل سليم', en: 'Verify monitoring, tracking, and camera readiness and function' },
  seat_belts: { ar: 'فحص سلامة المقاعد وأحزمة الأمان والتأكد من ثباتها وآلية القفل', en: 'Inspect seat and belt safety, stability, and locking mechanism' },
  fire_ext: { ar: 'التحقق من توفر طفاية الحريق وصلاحيتها وسهولة الوصول إليها', en: 'Verify fire extinguisher availability, validity, and accessibility' },
  safety_kit: { ar: 'التحقق من صلاحية الإسعافات الأولية واكتمال معداتها وتوفر جهاز AED', en: 'Verify first aid validity, complete equipment, and AED presence' },
  tools: { ar: 'التحقق من توفر أدوات الطوارئ مثل مثلث التحذير، المياه الاحتياطية، السترات العاكسة، والإضاءة الاحتياطية', en: 'Verify emergency tools like warning triangle, spare water, and vests' },
  comm_tools: { ar: 'التأكد من جاهزية وسائل الاتصال مثل الهاتف أو أجهزة الاتصال اللاسلكي', en: 'Ensure communication tools like phone or radio are ready' },
  load_securing: { ar: 'التحقق من تثبيت الحمولة أو الأمتعة بإحكام لمنع تحركها أثناء القيادة', en: 'Verify cargo or luggage is securely fastened to prevent movement' },
  vehicle_docs: { ar: 'التأكد من توفر وثائق المركبة الرسمية وسريانها', en: 'Ensure official vehicle documents are available and valid' },
  steering: { ar: 'التحقق من سلاسة حركة المقود وعدم وجود اهتزازات أو أصوات غير طبيعية', en: 'Check steering smoothness and no vibrations or abnormal sounds' },
  emergency_exits: { ar: 'فحص مخارج الطوارئ للتأكد من سلامتها وسهولة فتحها وعدم وجود عوائق', en: 'Inspect emergency exits for safety, ease of opening, and no obstructions' },
};

export const ELECTRIC_TOOLTIPS: Record<string, { ar: string, en: string }> = {
  ...CHECKLIST_TOOLTIPS,
  battery: { ar: 'فحص البطارية المساعدة (12V) والتأكد من سلامة الأقطاب وعدم وجود تآكل أو ضعف في التشغيل', en: 'Check 12V auxiliary battery stability, terminal safety, and no corrosion or weak start' },
  fluid_leaks: { ar: 'فحص أسفل المركبة للتأكد من عدم وجود تسريب لسائل تبريد البطارية أو سائل الفرامل', en: 'Check under vehicle for battery coolant or brake fluid leaks' },
  ev_hv_battery: { ar: 'فحص بطارية الجهد العالي (HV) للتأكد من سلامة التوصيلات وعدم وجود تسريب أو تلف في العازل', en: 'Inspect HV battery for safe connections, no leaks, and intact insulation' },
  high_voltage_battery: { ar: 'التحقق من عدم وجود رسائل تحذيرية أو أعطال مرتبطة ببطارية الجهد العالي في شاشة المركبة.', en: 'Verify there are no warning messages or faults related to the high voltage battery on the vehicle screen.' },
  high_voltage_cables: { ar: 'التأكد من سلامة كابلات الجهد العالي (ذات اللون البرتقالي) وعدم وجود تشققات أو تلف في العزل.', en: 'Ensure high voltage cables (orange) are intact and have no cracks or insulation damage.' },
  ev_charge_level: { ar: 'التحقق من أن مستوى شحن البطارية كافٍ لتشغيل المركبة وإتمام الرحلات المخطط لها.', en: 'Verify that the battery charge level is sufficient to operate the vehicle and complete planned trips.' },
  tire_repair_kit: { ar: 'التحقق من وجود أداة إصلاح الإطارات ومضخة الهواء في مكانها وسلامتها للاستخدام عند الحاجة.', en: 'Verify the presence and condition of the tire repair kit and air pump for use in emergencies.' },
  luggage: { ar: 'فحص منطقة الأمتعة والتأكد من ترتيبها وعدم وجود أدوات حادة أو خطرة قد تضر ببطارية الجهد العالي أو هيكل المركبة.', en: 'Inspect the luggage area to ensure it is organized and free of sharp or hazardous items that could damage the high voltage battery or vehicle structure.' },
  ev_charging_port: { ar: 'التحقق من سلامة منفذ الشحن وعدم وجود تلف أو تآكل أو شوائب قد تؤثر على عملية الشحن.', en: 'Verify the integrity of the charging port and ensure no damage, corrosion, or debris affects the charging process.' },
  battery_coolant: { ar: 'التأكد من مستوى سائل تبريد البطارية وعدم وجود تسريبات أو انخفاض غير طبيعي.', en: 'Ensure battery coolant level and no leaks or abnormal drop.' },
  charging_cable: { ar: 'فحص كابل الشحن والتأكد من سلامة العازل والموصلات وعدم وجود تلف أو تشققات.', en: 'Inspect charging cable and ensure insulation and connectors are intact without damage or cracks.' },
  bms_system: { ar: 'التأكد من عدم وجود رسائل تحذيرية أو أعطال مرتبطة بنظام إدارة البطارية.', en: 'Ensure there are no warning messages or faults related to the battery management system (BMS).' },
  indicators: { ar: 'التأكد من عمل إشارات الانعطاف الأمامية والخلفية بصورة صحيحة وواضحة.', en: 'Ensure front and rear turn signals work correctly and clearly.' },
  ev_electric_motor: { ar: 'فحص المحرك الكهربائي والتأكد من عدم وجود أصوات غير طبيعية أو اهتزازات أو تسريبات.', en: 'Inspect the electric motor for abnormal sounds, vibrations, or leaks.' },
  ev_thermal_system: { ar: 'فحص نظام التبريد الحراري للبطارية والتأكد من عمل المضخات والمراوح والأنابيب بشكل سليم.', en: 'Inspect the battery thermal management system, ensuring pumps, fans, and lines function correctly.' },
  ev_insulation: { ar: 'فحص سلامة العزل الكهربائي للمكونات ذات الجهد العالي والتأكد من عدم وجود تآكل أو تلف.', en: 'Check electrical insulation integrity of high voltage components for corrosion or damage.' },
  ev_undercarriage: { ar: 'فحص أسفل المركبة والتأكد من سلامة غلاف حماية البطارية وعدم وجود خدوش أو ثقوب.', en: 'Inspect vehicle undercarriage and battery protection shield for scratches, dents, or punctures.' },
  ev_12v_system: { ar: 'فحص نظام 12 فولت المساعد والتأكد من سلامة البطارية الصغيرة وتوصيلاتها.', en: 'Inspect the 12V auxiliary system, ensuring the small battery and connections are in good condition.' },
  ev_drive_modes: { ar: 'التحقق من عمل جميع أوضاع القيادة (Eco/Normal/Sport) والتبديل بينها بشكل صحيح.', en: 'Verify all drive modes (Eco/Normal/Sport) function and switch correctly.' },
  ev_onboard_charger: { ar: 'فحص الشاحن الداخلي للمركبة والتأكد من سلامته وعدم وجود رسائل خطأ.', en: 'Inspect the onboard charger for proper operation with no error messages.' },
  frunk: { ar: 'فحص الصندوق الأمامي (Frunk) والتأكد من نظافته وسلامة آلية الفتح والإغلاق.', en: 'Inspect the frunk (front trunk), ensuring cleanliness and proper open/close mechanism.' },
  regen_braking: { ar: 'فحص نظام الفرملة المتجددة والتأكد من استجابته وكفاءة استرداد الطاقة.', en: 'Test regenerative braking system responsiveness and energy recovery efficiency.' },
  doors: { ar: 'فحص أبواب المركبة والتأكد من سلاسة فتحها وإغلاقها وسلامة الأقفال الإلكترونية', en: 'Inspect vehicle doors to ensure smooth opening and closing and the integrity of electronic locks' },
  parking_brake: { ar: 'التحقق من كفاءة عمل مكابح الركن الإلكترونية (EPB) واستجابتها الفورية للتفعيل والإلغاء', en: 'Verify the efficiency of the Electronic Parking Brake (EPB) and its instant response to engagement and release' },
  gear_selector: { ar: 'فحص استجابة مبدل السرعة الإلكتروني وتنقله بين وضعيات القيادة دون أخطاء', en: 'Check the responsiveness of the electronic gear selector and its shifting between drive modes without errors' },
};
