import React from 'react';

/**
 * ReportPageFooter displays a small, faint watermark at the bottom of printed report pages.
 */
export const ReportPageFooter: React.FC = () => (
  <div className="absolute bottom-4 left-0 right-0 text-center pointer-events-none opacity-25">
    <p className="text-[7px] font-black tracking-[0.4em] uppercase text-gray-400">
      Generated by VI System
    </p>
  </div>
);
