import React from 'react';

/**
 * ReportPageFooter displays a unified standard text at the bottom of printed report pages.
 */
interface Props {
  isRTL?: boolean;
  lang?: string;
  pageNumber?: number;
  totalPages?: number;
  showText?: boolean;
}

export const ReportPageFooter: React.FC<Props> = ({ 
  isRTL = true, 
  lang, 
  pageNumber = 1, 
  totalPages = 1, 
  showText = true 
}) => {
  if (!showText) return null;

  return (
    <div className="absolute bottom-6 w-full left-0 px-10">
      <div className="flex items-center justify-between border-t border-gray-100 pt-3 text-[10px]">
        <div className="text-gray-400 font-normal">
          {isRTL 
            ? 'تم إنشاء هذا التقرير إلكترونيًا بواسطة نظام فحص المركبات (VIS)' 
            : 'This report was generated by the Vehicle Inspection System (VIS)'}
        </div>
        <div className="text-gray-500 font-bold">
          {isRTL 
            ? `صفحة ${pageNumber} من ${totalPages}` 
            : `Page ${pageNumber} of ${totalPages}`}
        </div>
      </div>
    </div>
  );
};
