import React from 'react';
import { DriverReadiness, VehicleType, ReadinessQuestionDef } from "./types";
import { 
  BatteryFull, 
  Volume2, 
  ShieldCheck, 
  Fuel, 
  Waves, 
  Lightbulb, 
  ArrowLeftRight, 
  Eye, 
  CircleDot, 
  IdCard, 
  Car, 
  Disc, 
  Gauge, 
  Droplets, 
  Droplet, 
  Flame, 
  BriefcaseMedical, 
  Wrench, 
  Snowflake, 
  Cctv,
  Moon,
  Coffee,
  Navigation,
  Stethoscope,
  MapPin,
  Siren,
  CloudLightning,
  Shield,
  Timer,
  FileCheck,
  CircleDashed,
  Radio,
  Package,
  PhoneOff,
  LifeBuoy,
  LogOut,
  DoorOpen,
  Settings,
  AlertTriangle,
  LightbulbOff,
  ShieldAlert,
  HelpCircle,
  Triangle,
  PhoneCall,
  UserCheck,
  Map,
  Thermometer,
  Smartphone,
  Anchor,
  Pill,
  CloudSunRain,
  ClipboardCheck,
  BedDouble,
  BatteryCharging,
  Zap,
  PlugZap
} from 'lucide-react';

// Helper to create image-based icons with normalized visual sizing and blue color filtering
const ImageIcon = (url: string, alt: string) => ({ size = 20, className = "" }: { size?: number, className?: string }) => (
  React.createElement('div', {
    style: { 
      width: size, 
      height: size, 
      display: 'flex', 
      alignItems: 'center', 
      justifyContent: 'center',
      padding: '1px'
    },
    className: className,
  }, 
    React.createElement('img', {
      src: url,
      style: { 
        maxWidth: '100%', 
        maxHeight: '100%', 
        objectFit: 'contain',
        filter: 'brightness(0) saturate(100%) invert(31%) sepia(94%) saturate(2335%) hue-rotate(184deg) brightness(92%) contrast(101%)'
      },
      alt: alt
    })
  )
);

// Custom image icons
const BatteryIcon = ImageIcon("https://i.postimg.cc/fRM2wBTv/car_battery.png", "Battery");
const HornIcon = ImageIcon("https://i.postimg.cc/Gmb7cqhx/horn.png", "Horn");
const FuelIcon = ImageIcon("https://i.postimg.cc/mDvxnFM2/gas_station_(1).png", "Fuel");
const WiperIcon = ImageIcon("https://i.postimg.cc/SN61FwqC/wiper.png", "Wiper");
const LampIcon = ImageIcon("https://i.postimg.cc/XYnHVQ7K/fog_lamp.png", "Lamp");
const FirstAidIcon = ImageIcon("https://i.postimg.cc/52f7xn21/first_aid_kit.png", "First Aid");
const SignalIcon = ImageIcon("https://i.postimg.cc/m2Ypf0R6/turn_signal.png", "Signal");
const MirrorIcon = ImageIcon("https://i.postimg.cc/xTvpDWYH/mirror.png", "Mirror");
const BrakesIcon = ImageIcon("https://i.postimg.cc/Qt2LzW5X/disc_brake.png", "Brakes");
const PlateIcon = ImageIcon("https://i.postimg.cc/bwDxyD2q/license-plate-(1).png", "Plate");
const VehicleBodyIcon = ImageIcon("https://i.postimg.cc/VNd1JwWX/inspection.png", "Vehicle Body");
const WheelIcon = ImageIcon("https://i.postimg.cc/yYmp4wBX/car_wheel.png", "Wheel");
const TyrePressureIcon = ImageIcon("https://i.postimg.cc/V6xyhbth/tyre-(1).png", "Tyre Pressure");
const FluidsIcon = ImageIcon("https://i.postimg.cc/Qdj4X0xy/water-tank.png", "Fluids");
const LeakIcon = ImageIcon("https://i.postimg.cc/rF1ZXvcS/car.png", "Leaks");
const FireExtIcon = ImageIcon("https://i.postimg.cc/bwqCz3wP/fire_extinguisher.png", "Fire Extinguisher");
const EmergencyToolsIcon = ImageIcon("https://i.postimg.cc/kXQY3k9s/car_repair.png", "Emergency Tools");
const ACIcon = ImageIcon("https://i.postimg.cc/B6L9NC83/air_conditioner.png", "AC");
const IVMSIcon = ImageIcon("https://i.postimg.cc/7Y3t8pDJ/connected_car.png", "IVMS System");
const DocumentsIcon = ImageIcon("https://i.postimg.cc/XJRMPyFS/registration.png", "Documents");
const SpareTyreIcon = ImageIcon("https://i.postimg.cc/FsyC52mS/car_with_spare_tire.png", "Spare Tyre");
const CommToolsIcon = ImageIcon("https://i.postimg.cc/d1kPn97K/smartphone.png", "Communication Tools");
const LuggageIcon = ImageIcon("https://i.postimg.cc/76G8XN5F/suitcase.png", "Luggage");
const SeatBeltIcon = ImageIcon("https://i.postimg.cc/Gh2qBH18/seabelt-SVG.png", "Seatbelt");
const SteeringIcon = ImageIcon("https://i.postimg.cc/FsVgtKvh/steering-wheel.png", "Steering Wheel");

export const INITIAL_READINESS: DriverReadiness = {
  declaration: false,
  finalConfirmation: false,
  answers: {},
  status: 'pending'
};

export const READINESS_QUESTIONS: ReadinessQuestionDef[] = [
  { id: 'q_jmp_tbt', key: 'q_jmp_tbt', critical: true, icon: Map },
  { id: 'q_rested', key: 'q_rested', critical: true, icon: BedDouble },
  { id: 'q_no_meds', key: 'q_no_meds', critical: true, icon: Pill },
  { id: 'q_break_plan', key: 'q_break_plan', critical: true, icon: Coffee },
  { id: 'q_vehicle_suitable', key: 'q_vehicle_suitable', critical: true, icon: ClipboardCheck },
  { id: 'q_emergency_kit', key: 'q_emergency_kit', critical: true, icon: Smartphone },
  { id: 'q_max_hours', key: 'q_max_hours', critical: true, icon: Timer },
  { id: 'q_gps_stop', key: 'q_gps_stop', critical: true, icon: Navigation },
  { id: 'q_emergency_proc', key: 'q_emergency_proc', critical: true, icon: LifeBuoy },
  { id: 'q_bad_weather', key: 'q_bad_weather', critical: true, icon: CloudSunRain },
];

export const VEHICLE_TYPES: { value: VehicleType; labelAr: string; labelEn: string }[] = [
  { value: 'light_vehicle', labelAr: 'مركبة خفيفة', labelEn: 'Light Vehicle' },
  { value: 'heavy_bus', labelAr: 'حافلة ثقيلة', labelEn: 'Heavy Bus' },
  { value: 'light_bus', labelAr: 'حافلة خفيفة', labelEn: 'Light Bus' },
  { value: 'ambulance', labelAr: 'سيارة إسعاف', labelEn: 'Ambulance' },
  { value: 'pickup', labelAr: 'سيارة بيك أب', labelEn: 'Pickup' },
  { value: 'electric_vehicle', labelAr: 'مركبة كهربائية', labelEn: 'Electric Vehicle' },
];

export const VEHICLE_IMAGES: Record<VehicleType, string> = {
  light_vehicle: "/assest/vehicles/landcruser.png",
  heavy_bus: "/assest/vehicles/heavybus.png",
  light_bus: "/assest/vehicles/coster.png",
  ambulance: "/assest/vehicles/ambulance.png",
  pickup: "/assest/vehicles/pickup.png",
  electric_vehicle: "/assest/vehicles/landcruser.png",
};

export const VEHICLE_SELECTION_IMAGES: Record<VehicleType, string> = {
  light_vehicle: "https://i.postimg.cc/wxbJZSRd/Land-Cruser-Copy.png",
  heavy_bus: "https://i.postimg.cc/nhmvv0zq/Heavy-Bus.jpg",
  light_bus: "https://i.postimg.cc/4y36VG7C/48691406-Copy.jpg",
  ambulance: "https://i.postimg.cc/QxHgMXZp/Ambulance-Copy.png",
  pickup: "https://i.postimg.cc/BvcHzb2t/toyota-hilux.jpg",
  electric_vehicle: "https://i.postimg.cc/wxbJZSRd/Land-Cruser-Copy.png",
};

// Generic Checklist - Exactly 24 items for Light, Ambulance, Light Bus, Pickup
export const GENERIC_CHECKLIST = [
  { id: 1, key: 'body_damage', icon: VehicleBodyIcon },
  { id: 2, key: 'plates', icon: PlateIcon },
  { id: 3, key: 'tyres', icon: WheelIcon },
  { id: 4, key: 'tyre_pressure', icon: TyrePressureIcon },
  { id: 5, key: 'spare_tire', icon: SpareTyreIcon },
  { id: 6, key: 'fluid_leaks', icon: LeakIcon },
  { id: 7, key: 'lights', icon: LampIcon },
  { id: 8, key: 'indicators', icon: SignalIcon },
  { id: 9, key: 'mirrors', icon: MirrorIcon },
  { id: 10, key: 'wipers', icon: WiperIcon },
  { id: 11, key: 'battery', icon: BatteryIcon },
  { id: 12, key: 'fluid_levels', icon: FluidsIcon },
  { id: 13, key: 'fuel', icon: FuelIcon },
  { id: 14, key: 'horn', icon: HornIcon },
  { id: 15, key: 'brakes', icon: BrakesIcon },
  { id: 16, key: 'ac', icon: ACIcon },
  { id: 17, key: 'monitoring_system', icon: IVMSIcon },
  { id: 18, key: 'seat_belts', icon: SeatBeltIcon },
  { id: 19, key: 'fire_ext', icon: FireExtIcon },
  { id: 20, key: 'safety_kit', icon: FirstAidIcon },
  { id: 21, key: 'tools', icon: EmergencyToolsIcon },
  { id: 22, key: 'comm_tools', icon: CommToolsIcon },
  { id: 23, key: 'load_securing', icon: LuggageIcon },
  { id: 24, key: 'vehicle_docs', icon: DocumentsIcon },
];

// Electric Vehicle Checklist - Exactly 24 items
// Replaces: fuel → ev_charge_level, fluid_levels → ev_hv_battery, load_securing → ev_charging_port
export const ELECTRIC_CHECKLIST = [
  { id: 1, key: 'body_damage', icon: VehicleBodyIcon },
  { id: 2, key: 'plates', icon: PlateIcon },
  { id: 3, key: 'tyres', icon: WheelIcon },
  { id: 4, key: 'tyre_pressure', icon: TyrePressureIcon },
  { id: 5, key: 'spare_tire', icon: SpareTyreIcon },
  { id: 6, key: 'fluid_leaks', icon: LeakIcon },
  { id: 7, key: 'lights', icon: LampIcon },
  { id: 8, key: 'indicators', icon: SignalIcon },
  { id: 9, key: 'mirrors', icon: MirrorIcon },
  { id: 10, key: 'wipers', icon: WiperIcon },
  { id: 11, key: 'battery', icon: BatteryIcon },
  { id: 12, key: 'ev_hv_battery', icon: BatteryCharging },
  { id: 13, key: 'ev_charge_level', icon: Zap },
  { id: 14, key: 'ev_charging_port', icon: PlugZap },
  { id: 15, key: 'horn', icon: HornIcon },
  { id: 16, key: 'brakes', icon: BrakesIcon },
  { id: 17, key: 'ac', icon: ACIcon },
  { id: 18, key: 'monitoring_system', icon: IVMSIcon },
  { id: 19, key: 'seat_belts', icon: SeatBeltIcon },
  { id: 20, key: 'fire_ext', icon: FireExtIcon },
  { id: 21, key: 'safety_kit', icon: FirstAidIcon },
  { id: 22, key: 'tools', icon: EmergencyToolsIcon },
  { id: 23, key: 'comm_tools', icon: CommToolsIcon },
  { id: 24, key: 'vehicle_docs', icon: DocumentsIcon },
];

// Specific Checklist for Heavy Bus - Exactly 24 items
export const HEAVY_BUS_CHECKLIST = [
  { id: 1, key: 'body_damage', icon: VehicleBodyIcon },
  { id: 2, key: 'tyres', icon: WheelIcon },
  { id: 3, key: 'tyre_pressure', icon: TyrePressureIcon },
  { id: 4, key: 'fluid_leaks', icon: LeakIcon },
  { id: 5, key: 'lights', icon: LampIcon },
  { id: 6, key: 'indicators', icon: SignalIcon },
  { id: 7, key: 'mirrors', icon: MirrorIcon },
  { id: 8, key: 'wipers', icon: WiperIcon },
  { id: 9, key: 'battery', icon: BatteryIcon },
  { id: 10, key: 'fluid_levels', icon: FluidsIcon },
  { id: 11, key: 'fuel', icon: FuelIcon },
  { id: 12, key: 'warning_alarms', icon: HornIcon },
  { id: 13, key: 'brakes', icon: BrakesIcon },
  { id: 14, key: 'ac', icon: ACIcon },
  { id: 15, key: 'monitoring_system', icon: IVMSIcon },
  { id: 16, key: 'seat_belts', icon: SeatBeltIcon },
  { id: 17, key: 'fire_ext', icon: FireExtIcon },
  { id: 18, key: 'safety_kit', icon: FirstAidIcon },
  { id: 19, key: 'tools', icon: EmergencyToolsIcon },
  { id: 20, key: 'comm_tools', icon: CommToolsIcon },
  { id: 21, key: 'load_securing', icon: LuggageIcon },
  { id: 22, key: 'vehicle_docs', icon: DocumentsIcon },
  { id: 23, key: 'steering', icon: SteeringIcon },
  { id: 24, key: 'emergency_exits', icon: LogOut },
];

export const CHECKLIST_STATUS_LABELS: Record<string, { pass: { ar: string, en: string }, fail: { ar: string, en: string } }> = {
  battery: { pass: { ar: 'مشحونة', en: 'Charged' }, fail: { ar: 'ضعيفة', en: 'Weak' } },
  horn: { pass: { ar: 'يعمل', en: 'Working' }, fail: { ar: 'لا يعمل', en: 'Not Working' } },
  warning_alarms: { pass: { ar: 'تعمل', en: 'Working' }, fail: { ar: 'لا تعمل', en: 'Not Working' } },
  seat_belts: { pass: { ar: 'سليمة', en: 'Intact' }, fail: { ar: 'تالفة', en: 'Damaged' } },
  fuel: { pass: { ar: 'كافٍ', en: 'Sufficient' }, fail: { ar: 'منخفض', en: 'Low' } },
  wipers: { pass: { ar: 'سليمة', en: 'Intact' }, fail: { ar: 'تالفة', en: 'Damaged' } },
  lights: { pass: { ar: 'تعمل', en: 'Working' }, fail: { ar: 'لا تعمل', en: 'Not Working' } },
  indicators: { pass: { ar: 'تعمل', en: 'Working' }, fail: { ar: 'لا تعمل', en: 'Not Working' } },
  mirrors: { pass: { ar: 'سليمة', en: 'Intact' }, fail: { ar: 'متضررة', en: 'Damaged' } },
  brakes: { pass: { ar: 'سليمة', en: 'Intact' }, fail: { ar: 'ضعيفة', en: 'Weak' } },
  plates: { pass: { ar: 'واضحة', en: 'Clear' }, fail: { ar: 'غير واضحة', en: 'Unclear' } },
  body_damage: { pass: { ar: 'سليم', en: 'Intact' }, fail: { ar: 'متضرر', en: 'Damaged' } },
  tyres: { pass: { ar: 'سليمة', en: 'Intact' }, fail: { ar: 'تالفة', en: 'Damaged' } },
  tyre_pressure: { pass: { ar: 'صحيح', en: 'Correct' }, fail: { ar: 'غير صحيح', en: 'Incorrect' } },
  fluid_leaks: { pass: { ar: 'لا توجد', en: 'No Leaks' }, fail: { ar: 'تسريب', en: 'Leaks' } },
  fluid_levels: { pass: { ar: 'مكتملة', en: 'Full' }, fail: { ar: 'ناقصة', en: 'Low' } },
  fire_ext: { pass: { ar: 'صالحة', en: 'Valid' }, fail: { ar: 'منتهية', en: 'Expired' } },
  safety_kit: { pass: { ar: 'مكتملة', en: 'Complete' }, fail: { ar: 'ناقصة', en: 'Incomplete' } },
  tools: { pass: { ar: 'مكتملة', en: 'Complete' }, fail: { ar: 'ناقصة', en: 'Incomplete' } },
  ac: { pass: { ar: 'بارد', en: 'Cool' }, fail: { ar: 'ضعيف', en: 'Weak' } },
  monitoring_system: { pass: { ar: 'يعمل', en: 'Working' }, fail: { ar: 'معطل', en: 'Faulty' } },
  vehicle_docs: { pass: { ar: 'صالحة', en: 'Valid' }, fail: { ar: 'منتهية', en: 'Expired' } },
  spare_tire: { pass: { ar: 'سليم', en: 'Intact' }, fail: { ar: 'تالف', en: 'Damaged' } },
  comm_tools: { pass: { ar: 'تعمل', en: 'Working' }, fail: { ar: 'لا تعمل', en: 'Not Working' } },
  load_securing: { pass: { ar: 'آمن', en: 'Secure' }, fail: { ar: 'غير امنه', en: 'Unsecured' } },
  steering: { pass: { ar: 'سليمة', en: 'Normal' }, fail: { ar: 'خلل', en: 'Faulty' } },
  emergency_exits: { pass: { ar: 'سليمة', en: 'Functional' }, fail: { ar: 'معطلة', en: 'Obstructed' } },
  doors_steps: { pass: { ar: 'سليمة', en: 'Safe' }, fail: { ar: 'تالفة', en: 'Unsafe' } },
  ev_hv_battery: { pass: { ar: 'سليمة', en: 'Normal' }, fail: { ar: 'خلل', en: 'Faulty' } },
  ev_charge_level: { pass: { ar: 'كافٍ', en: 'Sufficient' }, fail: { ar: 'منخفض', en: 'Low' } },
  ev_charging_port: { pass: { ar: 'سليم', en: 'Intact' }, fail: { ar: 'تالف', en: 'Damaged' } },
};

export const CHECKLIST_TOOLTIPS: Record<string, { ar: string, en: string }> = {
  body_damage: { ar: 'فحص الهيكل الخارجي للمركبة للتأكد من خلوه من الصدمات أو أي أضرار قد تؤثر على السلامة', en: 'Inspect external body to ensure no dents or damage affecting safety' },
  plates: { ar: 'التحقق من وجود لوحات المركبة وتثبيتها بشكل صحيح ووضوح الأرقام وعدم وجود تلف', en: 'Verify presence and secure fixing of plates with clear numbers and no damage' },
  tyres: { ar: 'فحص حالة الإطارات للتأكد من عدم وجود تآكل مفرط أو تشققات أو انتفاخ', en: 'Check tyre condition for excessive wear, cracks, or bulging' },
  tyre_pressure: { ar: 'التأكد من أن ضغط الهواء في الإطارات ضمن الحدود الموصى بها', en: 'Ensure tyre pressure is within recommended limits' },
  spare_tire: { ar: 'التحقق من توفر الإطار الاحتياطي وسلامته وجاهزيته للاستخدام عند الطوارئ', en: 'Confirm spare tyre availability, integrity, and emergency readiness' },
  fluid_leaks: { ar: 'فحص أسفل المركبة للتأكد من عدم وجود أي تسريب للزيوت أو السوائل', en: 'Check under vehicle for any oil or fluid leaks' },
  lights: { ar: 'التأكد من عمل جميع المصابيح الأمامية والخلفية', en: 'Ensure all front and rear lights are functional' },
  indicators: { ar: 'فحص إشارات الانعطاف وأضواء التحذير والتأكد من عملها بوضوح', en: 'Check turn signals and hazard lights for clarity and function' },
  mirrors: { ar: 'التحقق من سلامة ونظافة الزجاج الامامي والمرايا وإمكانية ضبطها لتوفير رؤية واضحة', en: 'Verify safety and cleanliness of windshield and mirrors with clear visibility' },
  wipers: { ar: 'فحص عمل مساحات الزجاج وسلامة الشفرات وتوفر ماء المساحات', en: 'Inspect wiper operation, blade integrity, and fluid availability' },
  battery: { ar: 'التحقق من ثبات البطارية وسلامة الأقطاب وعدم وجود تآكل أو ضعف في التشغيل', en: 'Check battery stability, terminal safety, and no corrosion or weak start' },
  fluid_levels: { ar: 'فحص مستويات السوائل الأساسية مثل زيت المحرك وسائل التبريد وزيت الفرامل', en: 'Check essential fluid levels like engine oil, coolant, and brake fluid' },
  fuel: { ar: 'التأكد من توفر كمية وقود كافية لإتمام الرحلة المخطط لها', en: 'Ensure sufficient fuel to complete the planned journey' },
  horn: { ar: 'التحقق من عمل البوق وصوت التنبيه بوضوح', en: 'Verify horn operation and clear alert sound' },
  brakes: { ar: 'التأكد من كفاءة عمل الفرامل وعدم وجود ضعف أو أصوات غير طبيعية', en: 'Ensure brake efficiency and no weakness or abnormal sounds' },
  ac: { ar: 'فحص نظام التكييف للتأكد من كفاءته وقدرته على التبريد', en: 'Inspect AC system for efficiency and cooling capacity' },
  monitoring_system: { ar: 'التأكد من توفر نظام المراقبة والتتبع والكاميرات', en: 'Ensure the monitoring and tracking system and cameras are present' },
  seat_belts: { ar: 'فحص سلامة المقاعد وأحزمة الأمان والتأكد من ثباتها وآلية القفل', en: 'Inspect seat and belt safety, stability, and locking mechanism' },
  fire_ext: { ar: 'التحقق من توفر طفاية الحريق وصلاحيتها وسهولة الوصول إليها', en: 'Verify fire extinguisher availability, validity, and accessibility' },
  safety_kit: { ar: 'التأكد من صلاحية حقيبة الإسعافات الأولية واكتمال محتوياتها الأساسية', en: 'Verify first aid kit validity and completion of basic contents' },
  tools: { ar: 'التحقق من توفر أدوات الطوارئ مثل مثلث التحذير والرافعة ومفتاح العجلات', en: 'Verify emergency tools like warning triangle, jack, and wheel wrench' },
  comm_tools: { ar: 'التأكد من جاهزية وسائل الاتصال مثل الهاتف أو أجهزة الاتصال', en: 'Ensure communication tools like phone or radio are ready' },
  load_securing: { ar: 'التحقق من تثبيت الحمولة أو الأمتعة بإحكام لمنع تحركها أثناء القيادة', en: 'Verify cargo or luggage is securely fastened to prevent movement' },
  vehicle_docs: { ar: 'التأكد من توفر وثائق المركبة الرسمية وسريانها', en: 'Ensure official vehicle documents are available and valid' },
  doors_steps: { ar: 'سلامة الأبواب ودرج الصعود', en: 'Safe doors and boarding steps' },
  emergency_exits: { ar: 'فحص مخارج الطوارئ وسهولة فتحها', en: 'Check functional emergency exits' },
  steering: { ar: 'فحص سلاسة حركة عجلة القيادة', en: 'Check smooth steering wheel' },
  warning_alarms: { ar: 'تحقق من عمل تنبيه الرجوع للخلف', en: 'Check reverse alarm operation' },
};

export const AMBULANCE_TOOLTIPS: Record<string, { ar: string, en: string }> = { ...CHECKLIST_TOOLTIPS };

export const HEAVY_BUS_TOOLTIPS: Record<string, { ar: string, en: string }> = {
  body_damage: { ar: 'فحص الهيكل الخارجي للمركبة للتأكد من خلوه من الصدمات أو أي أضرار قد تؤثر على السلامة', en: 'Inspect external body to ensure no dents or damage affecting safety' },
  tyres: { ar: 'فحص حالة الإطارات للتأكد من عدم وجود تآكل مفرط أو تشققات أو انتفاخ', en: 'Check tyre condition for excessive wear, cracks, or bulging' },
  tyre_pressure: { ar: 'التأكد من أن ضغط الهواء في الإطارات ضمن الحدود الموصى بها', en: 'Ensure tyre pressure is within recommended limits' },
  fluid_leaks: { ar: 'فحص أسفل المركبة للتأكد من عدم وجود أي تسريب للزيوت أو السوائل', en: 'Check under vehicle for any oil or fluid leaks' },
  lights: { ar: 'التأكد من عمل جميع المصابيح الأمامية والخلفية', en: 'Ensure all front and rear lights are functional' },
  indicators: { ar: 'فحص إشارات الانعطاف وأضواء التحذير والتأكد من عملها بوضوح', en: 'Check turn signals and hazard lights for clarity and function' },
  mirrors: { ar: 'التحقق من سلامة ونظافة الزجاج الامامي والمرايا وإمكانية ضبطها لتوفير رؤية واضحة', en: 'Verify safety and cleanliness of windshield and mirrors with clear visibility' },
  wipers: { ar: 'فحص عمل مساحات الزجاج وسلامة الشفرات وتوفر ماء المساحات', en: 'Inspect wiper operation, blade integrity, and fluid availability' },
  battery: { ar: 'التحقق من ثبات البطارية وسلامة الأقطاب وعدم وجود تآكل أو ضعف في التشغيل', en: 'Check battery stability, terminal safety, and no corrosion or weak start' },
  fluid_levels: { ar: 'فحص مستويات السوائل الأساسية مثل زيت المحرك، سائل التبريد، وزيت الفرامل', en: 'Check essential fluid levels like engine oil, coolant, and brake fluid' },
  fuel: { ar: 'التأكد من توفر كمية وقود كافية لإتمام الرحلة المخطط لها', en: 'Ensure sufficient fuel to complete the planned journey' },
  warning_alarms: { ar: 'التحقق من عمل البوق وتنبيه الرجوع إلى الخلف', en: 'Verify horn and reverse alarm operation' },
  brakes: { ar: 'التأكد من كفاءة عمل الفرامل وعدم وجود ضعف أو أصوات غير طبيعية', en: 'Ensure brake efficiency and no weakness or abnormal sounds' },
  ac: { ar: 'فحص نظام التكييف للتأكد من كفاءته وقدرته على التبريد', en: 'Inspect AC system for efficiency and cooling capacity' },
  monitoring_system: { ar: 'التحقق من جاهزية نظام المراقبة والتتبع والكاميرات وعمله بشكل سليم', en: 'Verify monitoring, tracking, and camera readiness and function' },
  seat_belts: { ar: 'فحص سلامة المقاعد وأحزمة الأمان والتأكد من ثباتها وآلية القفل', en: 'Inspect seat and belt safety, stability, and locking mechanism' },
  fire_ext: { ar: 'التحقق من توفر طفاية الحريق وصلاحيتها وسهولة الوصول إليها', en: 'Verify fire extinguisher availability, validity, and accessibility' },
  safety_kit: { ar: 'التحقق من صلاحية الإسعافات الأولية واكتمال معداتها وتوفر جهاز AED', en: 'Verify first aid validity, complete equipment, and AED presence' },
  tools: { ar: 'التحقق من توفر أدوات الطوارئ مثل مثلث التحذير، المياه الاحتياطية، السترات العاكسة، والإضاءة الاحتياطية', en: 'Verify emergency tools like warning triangle, spare water, and vests' },
  comm_tools: { ar: 'التأكد من جاهزية وسائل الاتصال مثل الهاتف أو أجهزة الاتصال اللاسلكي', en: 'Ensure communication tools like phone or radio are ready' },
  load_securing: { ar: 'التحقق من تثبيت الحمولة أو الأمتعة بإحكام لمنع تحركها أثناء القيادة', en: 'Verify cargo or luggage is securely fastened to prevent movement' },
  vehicle_docs: { ar: 'التأكد من توفر وثائق المركبة الرسمية وسريانها', en: 'Ensure official vehicle documents are available and valid' },
  steering: { ar: 'التحقق من سلاسة حركة المقود وعدم وجود اهتزازات أو أصوات غير طبيعية', en: 'Check steering smoothness and no vibrations or abnormal sounds' },
  emergency_exits: { ar: 'فحص مخارج الطوارئ للتأكد من سلامتها وسهولة فتحها وعدم وجود عوائق', en: 'Inspect emergency exits for safety, ease of opening, and no obstructions' },
};

export const ELECTRIC_TOOLTIPS: Record<string, { ar: string, en: string }> = {
  ...CHECKLIST_TOOLTIPS,
  battery: { ar: 'فحص البطارية المساعدة (12V) والتأكد من سلامة الأقطاب وعدم وجود تآكل أو ضعف في التشغيل', en: 'Check 12V auxiliary battery stability, terminal safety, and no corrosion or weak start' },
  fluid_leaks: { ar: 'فحص أسفل المركبة للتأكد من عدم وجود تسريب لسائل تبريد البطارية أو سائل الفرامل', en: 'Check under vehicle for battery coolant or brake fluid leaks' },
  ev_hv_battery: { ar: 'فحص بطارية الجهد العالي (HV) للتأكد من سلامة التوصيلات وعدم وجود تسريب أو تلف في العازل', en: 'Inspect HV battery for safe connections, no leaks, and intact insulation' },
  ev_charge_level: { ar: 'التأكد من أن مستوى الشحن (SOC%) كافٍ لإتمام الرحلة المخطط لها', en: 'Verify battery charge level (SOC%) is sufficient to complete the planned journey' },
  ev_charging_port: { ar: 'فحص منفذ الشحن والكابل للتأكد من سلامتهما وعدم وجود تلف أو تآكل', en: 'Check charging port and cable for integrity, no damage or corrosion' },
};

export const DRIVER_GUIDES = [
  { section: 'fatigue', icon: Moon, color: 'bg-purple-50 text-purple-600', titleKey: 'guide_sleep_title', textKey: 'guide_sleep_text' },
  { section: 'fatigue', icon: Coffee, color: 'bg-amber-50 text-amber-600', titleKey: 'guide_breaks_title', textKey: 'guide_breaks_text' },
  { section: 'rules', icon: Timer, color: 'bg-blue-50 text-blue-600', titleKey: 'guide_hours_title', textKey: 'guide_hours_text' },
  { section: 'rules', icon: MapPin, color: 'bg-indigo-50 text-indigo-600', titleKey: 'guide_gps_title', textKey: 'guide_gps_text' },
  { section: 'safety', icon: Shield, color: 'bg-red-50 text-red-600', titleKey: 'guide_belt_title', textKey: 'guide_belt_text' },
  { section: 'safety', icon: Siren, color: 'bg-orange-50 text-orange-600', titleKey: 'guide_emergency_title', textKey: 'guide_emergency_text' },
];

export const VEHICLE_GUIDES = [
  { icon: Disc, color: 'bg-blue-50 text-blue-600', titleKey: 'v_guide_tyre_title', textKey: 'v_guide_tyre_text' },
  { icon: Lightbulb, color: 'bg-amber-50 text-amber-600', titleKey: 'v_guide_light_title', textKey: 'v_guide_light_text' },
  { icon: Droplet, color: 'bg-emerald-50 text-emerald-600', titleKey: 'v_guide_fluid_title', textKey: 'v_guide_fluid_text' },
  { icon: CircleDot, color: 'bg-red-50 text-red-600', titleKey: 'v_guide_brake_title', textKey: 'v_guide_brake_text' },
  { icon: BatteryFull, color: 'bg-purple-50 text-purple-600', titleKey: 'v_guide_battery_title', textKey: 'v_guide_battery_text' },
  { icon: ShieldAlert, color: 'bg-orange-50 text-orange-600', titleKey: 'v_guide_kit_title', textKey: 'v_guide_kit_text' },
];

export const EMERGENCY_PROCEDURES = [
  { icon: MapPin, color: 'bg-red-50 text-red-600', titleKey: 'ep_stop_title', textKey: 'ep_stop_text' },
  { icon: AlertTriangle, color: 'bg-amber-50 text-amber-600', titleKey: 'ep_hazard_title', textKey: 'ep_hazard_text' },
  { icon: UserCheck, color: 'bg-blue-50 text-blue-600', titleKey: 'ep_vest_title', textKey: 'ep_vest_text' },
  { icon: Triangle, color: 'bg-orange-50 text-orange-600', titleKey: 'ep_triangle_title', textKey: 'ep_triangle_text' },
  { icon: PhoneCall, color: 'bg-emerald-50 text-emerald-600', titleKey: 'ep_contact_title', textKey: 'ep_contact_text' },
  { icon: ShieldAlert, color: 'bg-gray-50 text-gray-600', titleKey: 'ep_safety_title', textKey: 'ep_safety_text' },
];

export const PRE_TRIP_TIPS = [
  { icon: Map, color: 'bg-blue-50 text-blue-600', titleKey: 'pt_route_title', textKey: 'pt_route_text' },
  { icon: Thermometer, color: 'bg-amber-50 text-amber-600', titleKey: 'pt_weather_title', textKey: 'pt_weather_text' },
  { icon: Smartphone, color: 'bg-emerald-50 text-emerald-600', titleKey: 'pt_comm_title', textKey: 'pt_comm_text' },
  { icon: Droplet, color: 'bg-cyan-50 text-cyan-600', titleKey: 'pt_water_title', textKey: 'pt_water_text' },
  { icon: Anchor, color: 'bg-indigo-50 text-indigo-600', titleKey: 'pt_cargo_title', textKey: 'pt_cargo_text' },
  { icon: Settings, color: 'bg-purple-50 text-purple-600', titleKey: 'pt_mirrors_title', textKey: 'pt_mirrors_text' },
];

export const TRANSLATIONS = {
  ar: {
    title: 'منصة السلامة الذكية للمركبات والسائقين',
    home: 'الرئيسية',
    inspections: 'الفحص',
    driver_guide: 'دليل السائق',
    vehicle_guide: 'سلامة المركبة',
    site_intro_title: 'مرحبًا بك في نظام الفحص الذكي للمركبات وجاهزية السائق',
    site_intro_body: 'اختر نوع الفحص المناسب للتأكد من جاهزيتك، وجاهزية المركبة، واستعدادك للرحلة قبل الانطلاق.',
    start_inspection_btn: 'بدء فحص جديد',
    mode_vehicle: 'فحص المركبة',
    mode_vehicle_desc: 'فحص شامل لحالة المركبة الخارجية والداخلية بدون رحلة.',
    mode_full: 'فحص المركبة وجاهزية السائق ',
    mode_full_desc: 'فحص متكامل للمركبة و جاهزية السائق قبل الرحلة',
    mode_driver: 'جاهزية السائق',
    mode_driver_desc: 'تقييم جاهزية السائق البدنية والذهنية للقيادة.',
    quick_access: 'وصول سريع',
    quick_access_desc: 'اختر نوع الفحص المناسب لك',
    resources: 'الموارد والإرشادات',
    emergency_proc_title: 'إجراءات الطوارئ',
    emergency_proc_desc: 'ماذا تفعل في حال وقوع حادث أو تعطل المركبة.',
    pre_trip_tips_title: 'نصائح قبل الرحلة',
    pre_trip_tips_desc: 'أفضل الممارسات للرحلات القصيرة والطويلة.',
    why_important_title: 'لماذا هذا الفحص مهم؟',
    why_important_1: 'يساعد على تقليل الحوادث والمخاطر',
    why_important_2: 'يضمن سلامة المركبة قبل الاستخدام',
    why_important_3: 'تقييم جاهزية السائق للقيادة',
    edit_report: 'تعديل التقرير',
    save_changes: 'حفظ التعديلات',
    download_image: 'تحميل كصورة',
    share_report: 'مشاركة التقرير',
    print_report: 'طباعة التقرير',
    risk_level: 'مستوى الأمان',
    risk_safe: 'آمن',
    risk_attention: 'انتبه',
    risk_high: 'خطر',
    saving: 'جاري الحفظ...',
    auto_saved: 'تم الحفظ تلقائياً',
    pre_trip_assist_title: 'مساعد الرحلة الذكي',
    pre_trip_msg_1: 'تأكد من أنك أخذت قسطاً كافياً من الراحة قبل البدء.',
    pre_trip_msg_2: 'شرب الماء وفترات الراحة تقلل من مخاطر الإرهاق.',
    driver_info: 'البيانات الأساسية',
    driver_name: 'اسم السائق',
    assistant_name: 'اسم السائق المساعد',
    assistant_phone: 'رقم تواصل المساعد',
    plate_number: 'رقم اللوحة',
    phone_number: 'رقم التواصل',
    odometer: 'قراءة العداد الحالية ',
    vehicle_type: 'نوع المركبة',
    next_inspection_date: 'تاريخ الفحص القادم',
    vehicle_expiry_date: 'تاريخ انتهاء رخصة المركبة',
    next: 'التالي',
    back: 'عودة',
    cancel: 'إلغاء',
    driver_readiness: 'جاهزية السائق',
    checklist: 'قائمة الفحص',
    pass: 'سليم',
    fail: 'غير سليم',
    warning: 'تنبيه',
    notes: 'ملاحظات',
    summary: 'ملخص الفحص',
    required: 'مطلوب',
    tap_to_mark: 'اضغط لتحديد الضرر',
    mark_all_safe: 'تحديد الكل كسليم',
    clear_markers: 'مسح جميع العلامات',
    readiness_declaration_text: 'حرصًا على سلامتك وسلامة الآخرين، صُمّم هذا القسم للتأكد من جاهزيتك قبل الانطلاق من حيث الراحة والتركيز والالتزام بإجراءات السلامة ومعرفتك بكيفية التصرف عند الطوارئ. نرجو قراءة كل سؤال بعناية والإجابة عليه بدقة وصراحة.',
    readiness_agree: 'أؤكد وأوافق',
    readiness_final_confirm: 'أؤكد أن جميع الإجابات دقيقة وأنا جاهز لهذه الرحلة',
    final_result_label: 'النتيجة النهائية',
    ready_for_trip: 'جاهز للرحلة',
    not_ready_label: 'غير جاهز للرحلة',
    yes: 'نعم',
    no: 'لا',
    pdf_report_title: 'نوع الفحص',
    pdf_checklist_title: 'قائمة عناصر الفحص',
    pdf_generated_on: 'تم الإنشاء في',
    evidence_notes_pdf: 'الأدلة والملاحظات والمرفقات',
    new_inspection: 'فحص جديد',
    coming_soon_ocr: 'قريباً: التقاط القراءة بالكاميرا',
    why_important: 'لماذا هذا مهم؟',
    ready: 'جاهز',
    not_ready: 'غير جاهز',
    pending: 'قيد الانتظار',
    body_damage: 'هيكل المركبة',
    battery: 'البطارية',
    horn: 'البوق',
    warning_alarms: 'إنذارات التحذير',
    seat_belts: 'المقاعد وأحزمة الأمان',
    fuel: 'الوقود',
    wipers: 'المساحات',
    lights: 'المصابيح',
    indicators: 'الإشارات',
    mirrors: 'المرايا والزجاج الامامي',
    brakes: 'الفرامل',
    plates: 'اللوحات',
    tyres: 'الإطارات',
    tyre_pressure: 'ضغط الإطارات',
    fluid_leaks: 'التسريبات',
    fluid_levels: 'مستوى السوائل',
    fire_ext: 'طفاية الحريق',
    safety_kit: 'الأدوات الطبية',
    tools: 'أدوات الطوارئ',
    ac: 'نظام التكييف',
    monitoring_system: 'نظام المراقبة و التتبع',
    vehicle_docs: 'وثائق المركبة',
    spare_tire: 'الإطار الاحتياطي',
    comm_tools: 'وسائل الاتصال',
    load_securing: 'الأمتعة',
    steering: 'عجلة القيادة',
    emergency_exits: 'مخارج الطوارئ',
    doors_steps: 'الأبواب ودرج الصعود',
    ev_hv_battery: 'بطارية الجهد العالي',
    ev_charge_level: 'مستوى الشحن',
    ev_charging_port: 'منفذ الشحن',
    q_jmp_tbt: 'أنا على علم بمحتوى خطة الرحلة وتلقيت تنبيهات الأمن والسلامة',
    q_rested: 'أشعر بالارتياح، نمت جيدا، وأنا مستعد لتولي هذه الرحلة',
    q_no_meds: 'لم أتناول أي عقاقير أو أدوية أو مخدرات قد تؤثر في قدرتي على القيادة',
    q_break_plan: 'يتضمن جدول الرحلة فترات راحة، وسأحرص على تناول الطعام وشرب الماء، خاصة في الرحلات التي تتجاوز مدتها ساعتين',
    q_vehicle_suitable: 'قمت بفحص المركبة وتأكدت من أنها تعمل بشكل جيد ولا توجد بها أي أعطال خطيرة وتناسب ظروف الطقس والطريق',
    q_emergency_kit: 'أمتلك هاتفا محمولا، ومجموعة طوارئ، بالإضافة إلى رخصة قيادة سارية المفعول وتأمين شامل',
    q_max_hours: 'أدرك ان الحد الأقصى المسموح به للقيادة في غضون 24 ساعة هو 10 ساعات',
    q_gps_stop: 'أدرك أن جهاز الملاحة الفضائية لا يمكن ضبطه أو إعادة ضبطه إلا بعد توقف السيارة بشكل آمن',
    q_emergency_proc: 'أنا على دراية بإجراءات الطوارئ اللازمة في حالة وقوع حادث أو عطل',
    q_bad_weather: 'أدرك كيفية القيادة في الظروف الجوية السيئة مثل المطر الغزير أو العواصف الرملية',
    q_phone: 'أتعهد بعدم استخدام الهاتف النقال أثناء القيادة، والالتزام باستخدامه فقط بعد التوقف الآمن للمركبة',
    guide_sleep_title: 'النوم الكافي',
    guide_sleep_text: 'احصل على 7-8 ساعات من النوم قبل الرحلات الطويلة.',
    guide_breaks_title: 'فترات الراحة',
    guide_breaks_text: 'توقف للاستراحة لمدة 15 دقيقة كل ساعتين من القيادة.',
    guide_hours_title: 'ساعات العمل',
    guide_hours_text: 'لا تتجاوز 10 ساعات قيادة في اليوم الواحد.',
    guide_gps_title: 'استخدام الملاحة',
    guide_gps_text: 'اضبط وجهتك قبل التحرك ولا تستخدم الهاتف أثناء القيادة.',
    guide_belt_title: 'حزام الأمان',
    guide_belt_text: 'تأكد من ارتداء حزام الأمان لك ولجميع الركاب.',
    guide_emergency_title: 'حالات الطوارئ',
    guide_emergency_text: 'احتفظ بأرقام الطوارئ ومكان حقيبة الإسعافات في متناول اليد.',
    v_guide_tyre_title: 'سلامة الإطارات',
    v_guide_tyre_text: 'افحص تآكل الإطارات وضغط الهواء بانتظام لتجنب الانفجار المفاجئ.',
    v_guide_light_title: 'نظام الإضاءة',
    v_guide_light_text: 'تأكد من نظافة وعمل جميع المصابيح لتكون مرئياً للآخرين.',
    v_guide_fluid_title: 'السوائل والمحرك',
    v_guide_fluid_text: 'مراقبة مستويات الزيت وسائل التبريد تمنع تعطل المحرك في الطريق.',
    v_guide_brake_title: 'نظام الفرامل',
    v_guide_brake_text: 'تأكد من كفاءة استجابة الفرامل وعدم وجود أصوات غريبة لضمان التوقف الآمن.',
    v_guide_battery_title: 'البطارية والكهرباء',
    v_guide_battery_text: 'افحص سلامة البطارية والتوصيلات لتجنب تعطل المركبة المفاجئ أثناء الرحلة.',
    v_guide_kit_title: 'أدوات الطوارئ',
    v_guide_kit_text: 'تأكد من وجود طفاية الحريق، حقيبة الإسعاف، ومثلث التحذير لضمان الجاهزية.',
    ep_stop_title: 'التوقف الآمن',
    ep_stop_text: 'أوقف المركبة في مكان آمن بعيداً عن حركة السير قدر الإمكان.',
    ep_hazard_title: 'أضواء التحذير',
    ep_hazard_text: 'قم بتشغيل أضواء التحذير الرباعية فوراً لتنبيه السائقين الآخرين.',
    ep_vest_title: 'سترة السلامة',
    ep_vest_text: 'ارتدِ سترة السلامة العاكسة قبل الخروج من المركبة لزيادة وضوحك.',
    ep_triangle_title: 'مثلث التحذير',
    ep_triangle_text: 'ضع مثلث التحذير على مسافة كافية خلف المركبة (50-100 متر).',
    ep_contact_title: 'طلب المساعدة',
    ep_contact_text: 'اتصل برقم الطوارئ أو المشرف المسؤول للإبلاغ عن الحالة.',
    ep_safety_title: 'مكان آمن',
    ep_safety_text: 'ابتعد عن مسار الطريق ولا تبقَ داخل المركبة إذا كان هناك خطر تصادم.',
    pt_route_title: 'تخطيط المسار',
    pt_route_text: 'تعرف على وجهتك، أماكن الاستراحة، ومحطات الوقود المتاحة مسبقاً.',
    pt_weather_title: 'حالة الطقس',
    pt_weather_text: 'تأكد من ملاءمة حالة الطقس للقيادة وجهوزية المركبة للظروف الجوية.',
    pt_comm_title: 'وسائل الاتصال',
    pt_comm_text: 'تأكد من شحن هاتفك وتوفر شاحن للسيارة وسيلة تواصل بديلة.',
    pt_water_title: 'الماء والترطيب',
    pt_water_text: 'احتفظ بكمية كافية من مياه الشرب لتجنب الجفاف أثناء القيادة.',
    pt_cargo_title: 'تأمين الحمولة',
    pt_cargo_text: 'تأكد من تثبيت جميع الأغراض والحمولة بشكل يحول دون تحركها.',
    pt_mirrors_title: 'ضبط الوضعية',
    pt_mirrors_text: 'اضبط المقعد والمرايا لتوفير رؤية واضحة ومريحة قبل التحرك.',
  },
  en: {
    title: 'Smart Safety Platform for Vehicles and Drivers',
    home: 'Home',
    inspections: 'Inspection',
    driver_guide: 'Driver Guide',
    vehicle_guide: 'Vehicle Safety',
    site_intro_title: 'Welcome to the Smart Vehicle Inspection & Driver Readiness System',
    site_intro_body: 'Choose the appropriate inspection type to ensure your readiness and vehicle status before starting your journey.',
    start_inspection_btn: 'Start New Inspection',
    mode_vehicle: 'Vehicle Inspection',
    mode_vehicle_desc: 'Comprehensive inspection of external and internal vehicle condition.',
    mode_full: 'Vehicle & Driver Readiness',
    mode_full_desc: 'Integrated inspection to ensure vehicle safety and driver readiness.',
    mode_driver: 'Driver Readiness',
    mode_driver_desc: 'Assessment of physical and mental readiness for driving.',
    quick_access: 'Quick Access',
    quick_access_desc: 'Choose your inspection type',
    resources: 'Resources & Guidelines',
    emergency_proc_title: 'Emergency Procedures',
    emergency_proc_desc: 'What to do in case of an accident or vehicle breakdown.',
    pre_trip_tips_title: 'Pre-Trip Tips',
    pre_trip_tips_desc: 'Best practices for safe trips.',
    why_important_title: 'Why is this inspection important?',
    why_important_1: 'Reduces accidents and risks',
    why_important_2: 'Ensures vehicle safety',
    why_important_3: 'Assesses driver readiness',
    edit_report: 'Edit Report',
    save_changes: 'Save Changes',
    download_image: 'Download Image',
    share_report: 'Share Report',
    print_report: 'Print Report',
    risk_level: 'Safety Level',
    risk_safe: 'Safe',
    risk_attention: 'Attention',
    risk_high: 'Danger',
    saving: 'Saving...',
    auto_saved: 'Auto-saved',
    pre_trip_assist_title: 'Smart Trip Assistant',
    pre_trip_msg_1: 'Ensure you are well-rested before starting.',
    pre_trip_msg_2: 'Staying hydrated and taking breaks reduces fatigue.',
    driver_info: 'BASIC INFORMATION',
    driver_name: 'Driver Name',
    assistant_name: 'Driver Assistant Name',
    assistant_phone: 'Assistant Phone No.',
    plate_number: 'Plate No.',
    phone_number: 'Phone Number',
    odometer: 'Odometer',
    vehicle_type: 'Vehicle',
    next_inspection_date: 'Next Inspection Date',
    vehicle_expiry_date: 'Vehicle Expiry Date',
    next: 'Next',
    back: 'Back',
    cancel: 'Cancel',
    driver_readiness: 'Readiness',
    checklist: 'Checklist',
    pass: 'Pass',
    fail: 'Fail',
    warning: 'Warning',
    notes: 'Notes',
    summary: 'Summary',
    required: 'Required',
    tap_to_mark: 'Tap to mark damage',
    mark_all_safe: 'Mark All Safe',
    clear_markers: 'Clear Markers',
    readiness_declaration_text: "For your safety and the safety of others, please confirm your pre-departure readiness and knowledge of emergency procedures.",
    readiness_agree: 'I Agree',
    readiness_final_confirm: 'I confirm all answers are accurate and I am ready',
    final_result_label: 'Final Result',
    ready_for_trip: 'Ready for Trip',
    not_ready_label: 'Not Ready for Trip',
    yes: 'Yes',
    no: 'No',
    pdf_report_title: 'Inspection Type',
    pdf_checklist_title: 'Inspection Checklist',
    pdf_generated_on: 'Generated on',
    evidence_notes_pdf: 'Evidence & Notes',
    new_inspection: 'New Inspection',
    coming_soon_ocr: 'OCR Coming Soon',
    why_important: 'Why is this important?',
    ready: 'Ready',
    not_ready: 'Not Ready',
    pending: 'Pending',
    body_damage: 'Vehicle Body',
    battery: 'Battery',
    horn: 'Horn',
    warning_alarms: 'Warning Alarms',
    seat_belts: 'Seats & Seat Belts',
    fuel: 'Fuel',
    wipers: 'Wipers',
    lights: 'Lights',
    indicators: 'Indicators',
    mirrors: 'Mirrors & Windshield',
    brakes: 'Brakes',
    plates: 'Plates',
    tyres: 'Tyres',
    tyre_pressure: 'Tyre Pressure',
    fluid_leaks: 'Fluid Leaks',
    fluid_levels: 'Fluid Levels',
    fire_ext: 'Fire Extinguisher',
    safety_kit: 'Safety Kit',
    tools: 'Emergency Tools',
    ac: 'AC',
    monitoring_system: 'Monitoring System',
    vehicle_docs: 'Vehicle Documents',
    spare_tire: 'Spare Tyre',
    comm_tools: 'Communication Tools',
    load_securing: 'Luggage',
    steering: 'Steering Wheel',
    emergency_exits: 'Emergency Exits',
    doors_steps: 'Doors & Steps',
    ev_hv_battery: 'HV Battery',
    ev_charge_level: 'Charge Level',
    ev_charging_port: 'Charging Port',
    q_jmp_tbt: 'I confirm that I am aware of the trip itinerary and have reviewed all safety and security instructions',
    q_rested: 'I feel comfortable, well-rested, and fully prepared to undertake this trip',
    q_no_meds: 'I confirm that I have not consumed any medication, substances, or drugs that could affect my ability to drive safely',
    q_break_plan: 'The trip schedule includes rest breaks, and I will ensure proper meals and hydration, especially on trips that exceed two hours',
    q_vehicle_suitable: 'I have inspected the vehicle and confirm that it is in good working condition, with no mechanical issues, and is suitable for the expected weather and road conditions',
    q_emergency_kit: 'I have my mobile phone, emergency equipment, a valid driving license, and comprehensive insurance coverage',
    q_max_hours: 'I understand that the maximum allowed driving time is 10 hours within a 24-hour period',
    q_gps_stop: 'I acknowledge that the satellite tracking device cannot be reset or restarted after the vehicle stops unless it is done safely',
    q_emergency_proc: 'I am familiar with the required emergency procedures in the event of an accident or vehicle breakdown',
    q_bad_weather: 'I understand how to drive safely under adverse weather conditions, such as heavy rain, fog, or sandstorms',
    q_phone: 'I commit to not using my mobile phone while driving and to using it only after the vehicle has come to a complete stop in a safe location',
    guide_sleep_title: 'Adequate Sleep',
    guide_sleep_text: 'Get 7-8 hours of sleep before long trips.',
    guide_breaks_title: 'Rest Breaks',
    guide_breaks_text: 'Stop for a 15-minute break every two hours.',
    guide_hours_title: 'Working Hours',
    guide_hours_text: 'Do not exceed 10 hours of driving per day.',
    guide_gps_title: 'GPS Navigation',
    guide_gps_text: 'Set destination before moving; no phone use while driving.',
    guide_belt_title: 'Seat Belts',
    guide_belt_text: 'Ensure all passengers wear seat belts.',
    guide_emergency_title: 'Emergencies',
    guide_emergency_text: 'Keep emergency numbers and first-aid kit location handy.',
    v_guide_tyre_title: 'Tyre Safety',
    v_guide_tyre_text: 'Check tyre wear and pressure regularly.',
    v_guide_light_title: 'Lighting System',
    v_guide_light_text: 'Ensure all lights are clean and functional.',
    v_guide_fluid_title: 'Fluids & Engine',
    v_guide_fluid_text: 'Monitoring oil and coolant prevents engine failure.',
    v_guide_brake_title: 'Braking System',
    v_guide_brake_text: 'Ensure efficient brake response and no strange noises.',
    v_guide_battery_title: 'Battery & Electrical',
    v_guide_battery_text: 'Check battery health to avoid unexpected failure.',
    v_guide_kit_title: 'Emergency Kit',
    v_guide_kit_text: 'Ensure fire extinguisher, first-aid, and triangle are present.',
    ep_stop_title: 'Safe Stopping',
    ep_stop_text: 'Stop in a safe place away from traffic.',
    ep_hazard_title: 'Hazard Lights',
    ep_hazard_text: 'Turn on four-way hazard lights immediately.',
    ep_vest_title: 'Safety Vest',
    ep_vest_text: 'Wear a reflective vest before exiting the vehicle.',
    ep_triangle_title: 'Warning Triangle',
    ep_triangle_text: 'Place triangle at a sufficient distance behind vehicle.',
    ep_contact_title: 'Call for Help',
    ep_contact_text: 'Contact emergency services or your supervisor.',
    ep_safety_title: 'Safe Area',
    ep_safety_text: 'Stay away from traffic and do not remain in vehicle if risky.',
    pt_route_title: 'Route Planning',
    pt_route_text: 'Plan your route, rest stops, and fuel stations.',
    pt_weather_title: 'Weather Check',
    pt_weather_text: 'Ensure weather is suitable and vehicle is ready.',
    pt_comm_title: 'Communication',
    pt_comm_text: 'Ensure phone is charged and car charger is available.',
    pt_water_title: 'Hydration',
    pt_water_text: 'Keep enough water to stay hydrated during driving.',
    pt_cargo_title: 'Secure Cargo',
    pt_cargo_text: 'Ensure all items are secured against movement.',
    pt_mirrors_title: 'Adjustment',
    pt_mirrors_text: 'Adjust seat and mirrors for a clear view before moving.',
  }
};
